// src/views/CookieExtractor.vue
<script setup>
import { ref, computed, onMounted } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { showToast } from "../lib/toast.js";
import { showConfirm } from "../lib/confirm.js";
import { t, tFormat } from "../lib/i18n.js";
import { friendlyError } from "../lib/errors.js";
import BrandIcons from "../icons/BrandIcons.vue";

const MAX_DISPLAY = 500;
const browsers = ref([]);
const selectedBrowser = ref(null);
const domainFilter = ref("");
const cookies = ref([]);
const extracting = ref(false);

async function loadBrowsers() {
  try {
    browsers.value = await invoke("get_supported_browsers");
    if (browsers.value.length > 0) {
      selectedBrowser.value = browsers.value[0].name;
    }
  } catch (err) {
    console.error("Failed to load browsers:", err);
    showToast(t("cookies.no_browsers"));
  }
}

async function extractCookies() {
  if (!selectedBrowser.value) {
    showToast(t("cookies.select_browser_first"));
    return;
  }
  const confirmed = await showConfirm(
    t("cookies.security_warning").replace("{browser}", selectedBrowser.value),
    t("cookies.security_warning_title")
  );
  if (!confirmed) return;

  extracting.value = true;
  try {
    const filter = domainFilter.value.trim() || null;
    cookies.value = await invoke("extract_cookies", {
      browserName: selectedBrowser.value,
      domainFilter: filter,
      maxResults: null,
    });
  } catch (err) {
    showToast(t("cookies.extract_failed").replace("{error}", friendlyError(err)));
    cookies.value = [];
  } finally {
    extracting.value = false;
  }
}

async function exportNetscape() {
  try {
    const filter = domainFilter.value.trim() || null;
    const content = await invoke("export_as_netscape", {
      browserName: selectedBrowser.value,
      domainFilter: filter,
    });
    downloadFile(content, `cookies_${selectedBrowser.value.toLowerCase()}.txt`, "text/plain");
    showToast(t("cookies.export_netscape_ok"));
  } catch (err) {
    showToast(t("cookies.export_failed").replace("{error}", friendlyError(err)));
  }
}

async function exportJSON() {
  try {
    const filter = domainFilter.value.trim() || null;
    const content = await invoke("export_as_json", {
      browserName: selectedBrowser.value,
      domainFilter: filter,
    });
    downloadFile(content, `cookies_${selectedBrowser.value.toLowerCase()}.json`, "application/json");
    showToast(t("cookies.export_json_ok"));
  } catch (err) {
    showToast(t("cookies.export_failed").replace("{error}", friendlyError(err)));
  }
}

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function copyCookie(cookie) {
  const cookieString = `${cookie.name}=${cookie.value}`;
  navigator.clipboard
    .writeText(cookieString)
    .then(() => showToast(t("cookies.copy_single_ok")))
    .catch(() => showToast(t("common.copy_failed"), "error"));
}

function copyAllCookies() {
  const cookieStrings = cookies.value.map((c) => `${c.name}=${c.value}`).join("; ");
  navigator.clipboard
    .writeText(cookieStrings)
    .then(() => showToast(t("cookies.copy_all_ok")))
    .catch(() => showToast(t("common.copy_failed"), "error"));
}

function formatDate(timestamp) {
  if (timestamp === 0 || timestamp === null) return t("cookies.session");
  const date = new Date(timestamp * 1000);
  return date.toLocaleDateString();
}

const selectedBrowserCount = computed(() => {
  const b = browsers.value.find((b) => b.name === selectedBrowser.value);
  return b?.cookie_count || 0;
});

const columns = computed(() => [
  { title: t("cookies.name"), slotName: "name" },
  { title: t("cookies.value"), slotName: "value" },
  { title: t("cookies.domain"), slotName: "domain", width: 160 },
  { title: t("cookies.expires"), slotName: "expires", width: 120 },
  { title: t("cookies.actions"), slotName: "actions", align: "right", width: 70 },
]);

onMounted(() => {
  loadBrowsers();
});
</script>

<template>
  <div class="page cookie-page">
    <!-- Header -->
    <div class="page-header">
      <h1 class="page-title">{{ t("cookies.title") }}</h1>
      <p class="page-desc">{{ t("cookies.desc") }}</p>
    </div>

    <!-- Browser Selection -->
    <a-card :bordered="true" class="section-card mb-5">
      <div class="card-head-row">
        <h2 class="card-title">{{ t("cookies.select_browser") }}</h2>
        <span v-if="selectedBrowser" class="found-count">
          {{ selectedBrowserCount }} {{ t("cookies.found") }}
        </span>
      </div>

      <div class="browser-grid">
        <button
          v-for="browser in browsers"
          :key="browser.name"
          class="browser-card"
          :class="{ active: selectedBrowser === browser.name }"
          @click="selectedBrowser = browser.name"
        >
          <div class="browser-inner">
            <BrandIcons :name="browser.name.toLowerCase()" :size="28" class="browser-icon" />
            <div>
              <div class="browser-name">{{ browser.name }}</div>
              <div class="browser-count">{{ browser.cookie_count }} {{ t("cookies.cookies_label") }}</div>
            </div>
          </div>
        </button>
      </div>

      <a-alert v-if="browsers.length === 0" type="warning" class="mt-4">
        {{ t("cookies.no_browsers") }}
      </a-alert>
    </a-card>

    <!-- Filter and Extract -->
    <a-card :bordered="true" class="section-card mb-5">
      <div class="extract-row">
        <div class="filter-col">
          <label class="field-label">{{ t("cookies.domain_filter") }}</label>
          <a-input
            v-model="domainFilter"
            :placeholder="t('cookies.filter_placeholder')"
          />
        </div>
        <a-button
          type="primary"
          size="large"
          :loading="extracting"
          :disabled="!selectedBrowser"
          @click="extractCookies"
        >
          <template #icon><icon-download /></template>
          {{ extracting ? t("cookies.extracting") : t("cookies.extract") }}
        </a-button>
      </div>
    </a-card>

    <!-- Results -->
    <template v-if="cookies.length > 0">
      <a-alert
        v-if="cookies.length >= MAX_DISPLAY"
        type="warning"
        class="mb-4"
        :message="tFormat('cookies.display_limit', { count: MAX_DISPLAY })"
      />
      <a-card :bordered="true" class="section-card">
        <template #title>
          <div class="card-head-row">
            <span class="results-count">
              <span class="count-num">{{ cookies.length }}</span> {{ t("cookies.cookies_extracted") }}
            </span>
            <div class="toolbar-actions">
              <a-button size="small" @click="copyAllCookies">
                <template #icon><icon-copy /></template>
                {{ t("cookies.copy_all") }}
              </a-button>
              <a-button size="small" @click="exportJSON">
                <template #icon><icon-export /></template>
                {{ t("cookies.export_json") }}
              </a-button>
              <a-button size="small" @click="exportNetscape">
                <template #icon><icon-export /></template>
                {{ t("cookies.export_netscape") }}
              </a-button>
            </div>
          </div>
        </template>
        <a-table
          :data="cookies"
          :columns="columns"
          :pagination="false"
          :bordered="{ wrapper: false, cell: false }"
          size="small"
          :scroll="{ y: 384 }"
        >
          <template #name="{ record }">
            <span class="cookie-name" :title="record.name">{{ record.name }}</span>
          </template>
          <template #value="{ record }">
            <span class="cookie-value" :title="record.value">{{ record.value }}</span>
          </template>
          <template #domain="{ record }">
            <span class="cookie-domain">{{ record.domain }}</span>
          </template>
          <template #expires="{ record }">
            <span class="cookie-domain">{{ formatDate(record.expires) }}</span>
          </template>
          <template #actions="{ record }">
            <a-button type="text" size="mini" @click="copyCookie(record)" :title="t('cookies.copy_cookie')">
              <template #icon><icon-copy /></template>
            </a-button>
          </template>
        </a-table>
      </a-card>
    </template>

    <a-card
      v-else-if="!extracting && selectedBrowser"
      :bordered="true"
      class="empty-state"
    >
      <icon-cookie class="empty-icon" />
      <div class="empty-text">{{ t("cookies.no_cookies") }}</div>
      <div class="empty-hint">{{ t("cookies.extract_begin") }}</div>
      <div class="empty-warn">{{ t("cookies.extract_hint") }}</div>
    </a-card>
  </div>
</template>

<style scoped>
.section-card {
  border-radius: 10px;
}
.card-head-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}
.card-title {
  font-size: 14px;
  font-weight: 500;
  color: var(--color-text-1);
  margin: 0;
}
.found-count {
  font-size: 12px;
  color: var(--color-text-3);
}
.browser-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 12px;
  margin-top: 16px;
}
.browser-card {
  border: 1px solid var(--color-border-2);
  border-radius: 10px;
  padding: 12px;
  text-align: left;
  cursor: pointer;
  background-color: var(--color-fill-1);
  transition: all 0.15s;
}
.browser-card:hover {
  border-color: rgb(var(--primary-6), 0.6);
}
.browser-card.active {
  border-color: rgb(var(--primary-6));
  background-color: rgb(var(--primary-6), 0.08);
}
.browser-inner {
  display: flex;
  align-items: center;
  gap: 12px;
}
.browser-icon {
  color: var(--color-text-2);
}
.browser-card.active .browser-icon {
  color: rgb(var(--primary-6));
}
.browser-name {
  font-size: 14px;
  font-weight: 500;
  color: var(--color-text-1);
}
.browser-count {
  font-size: 12px;
  color: var(--color-text-3);
}
.extract-row {
  display: flex;
  align-items: flex-end;
  gap: 12px;
}
.filter-col {
  flex: 1;
}
.field-label {
  display: block;
  margin-bottom: 6px;
  font-size: 12px;
  color: var(--color-text-3);
}
.results-count {
  font-size: 14px;
  color: var(--color-text-1);
}
.count-num {
  font-weight: 600;
}
.toolbar-actions {
  display: flex;
  gap: 8px;
}
.cookie-name {
  font-size: 13px;
  font-weight: 500;
  color: var(--color-text-1);
  display: block;
  max-width: 200px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.cookie-value {
  font-family: "JetBrains Mono", monospace;
  font-size: 12px;
  color: var(--color-text-2);
  display: block;
  max-width: 300px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.cookie-domain {
  font-size: 12px;
  color: var(--color-text-3);
}
.empty-state {
  border-radius: 10px;
  padding: 32px;
  text-align: center;
}
.empty-icon {
  font-size: 36px;
  color: var(--color-text-4);
}
.empty-text {
  margin-top: 12px;
  font-size: 14px;
  color: var(--color-text-3);
}
.empty-hint {
  margin-top: 4px;
  font-size: 12px;
  color: var(--color-text-4);
}
.empty-warn {
  margin-top: 12px;
  font-size: 12px;
  color: rgb(var(--orange-6));
}
</style>

// src/routes/CookieExtractor.svelte
<script>
  import { invoke } from "@tauri-apps/api/core";
  import { onMount } from "svelte";
  import { showToast } from "../lib/toast.svelte.js";
  import { showConfirm } from "../lib/confirm.svelte.js";
  import BrandIcons from "../icons/BrandIcons.svelte";
  import { t } from "../lib/i18n.svelte.js";
  import { friendlyError } from "../lib/errors.svelte.js";

  const MAX_DISPLAY = 500;
  let browsers = $state([]);
  let selectedBrowser = $state(null);
  let domainFilter = $state("");
  let cookies = $state([]);
  let loading = $state(false);
  let extracting = $state(false);

  async function loadBrowsers() {
    try {
      browsers = await invoke("get_supported_browsers");
      if (browsers.length > 0) {
        selectedBrowser = browsers[0].name;
      }
    } catch (err) {
      console.error("Failed to load browsers:", err);
      showToast(t('cookies.no_browsers'));
    }
  }

  async function extractCookies() {
    if (!selectedBrowser) {
      showToast(t('cookies.select_browser_first'));
      return;
    }

    // 安全警告：用户必须确认了解风险后才可提取
    const confirmed = await showConfirm(
      t('cookies.security_warning').replace('{browser}', selectedBrowser),
      t('cookies.security_warning_title')
    );
    if (!confirmed) return;

    extracting = true;
    try {
      const filter = domainFilter.trim() || null;
      cookies = await invoke("extract_cookies", {
        browserName: selectedBrowser,
        domainFilter: filter,
        maxResults: null,
      });
    } catch (err) {
      showToast(t('cookies.extract_failed').replace('{error}', friendlyError(err)));
      cookies = [];
    } finally {
      extracting = false;
    }
  }

  async function exportNetscape() {
    try {
      const filter = domainFilter.trim() || null;
      const content = await invoke("export_as_netscape", {
        browserName: selectedBrowser,
        domainFilter: filter,
      });
      
      downloadFile(content, `cookies_${selectedBrowser.toLowerCase()}.txt`, 'text/plain');
      showToast(t('cookies.export_netscape_ok'));
    } catch (err) {
      showToast(t('cookies.export_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function exportJSON() {
    try {
      const filter = domainFilter.trim() || null;
      const content = await invoke("export_as_json", {
        browserName: selectedBrowser,
        domainFilter: filter,
      });
      
      downloadFile(content, `cookies_${selectedBrowser.toLowerCase()}.json`, 'application/json');
      showToast(t('cookies.export_json_ok'));
    } catch (err) {
      showToast(t('cookies.export_failed').replace('{error}', friendlyError(err)));
    }
  }

  function downloadFile(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function copyCookie(cookie) {
    const cookieString = `${cookie.name}=${cookie.value}`;
    navigator.clipboard.writeText(cookieString).then(() => {
      showToast(t('cookies.copy_single_ok'));
    }).catch(() => {
      showToast(t('common.copy_failed'), "error");
    });
  }

  function copyAllCookies() {
    const cookieStrings = cookies.map(c => `${c.name}=${c.value}`).join('; ');
    navigator.clipboard.writeText(cookieStrings).then(() => {
      showToast(t('cookies.copy_all_ok'));
    }).catch(() => {
      showToast(t('common.copy_failed'), "error");
    });
  }

  function formatDate(timestamp) {
    if (timestamp === 0 || timestamp === null) return t('cookies.session');
    const date = new Date(timestamp * 1000);
    return date.toLocaleDateString();
  }

  onMount(() => {
    loadBrowsers();
  });
</script>

<div class="mx-auto max-w-6xl p-5">
  <!-- Header -->
  <div class="mb-6">
    <h1 class="text-xl font-semibold text-nx-text">{t('cookies.title')}</h1>
    <p class="mt-1 text-xs text-nx-text-muted">{t('cookies.desc')}</p>
  </div>

  <!-- Browser Selection -->
  <div class="mb-6 nx-card p-5">
    <div class="mb-4 flex items-center justify-between">
      <h2 class="text-sm font-medium text-nx-text">{t('cookies.select_browser')}</h2>
      {#if selectedBrowser}
        <span class="text-xs text-nx-text-muted">
          {browsers.find(b => b.name === selectedBrowser)?.cookie_count || 0} {t('cookies.found')}
        </span>
      {/if}
    </div>

    <div class="grid grid-cols-3 gap-3">
      {#each browsers as browser}
        <button
          class="border px-4 py-3 text-left {selectedBrowser === browser.name
            ? 'border-nx-accent bg-nx-accent/10'
            : 'border-nx-border bg-nx-bg'}"
          onclick={() => selectedBrowser = browser.name}>
          <div class="flex items-center gap-3">
            <BrandIcons name={browser.name.toLowerCase()} size={28} class={'text-2xl ' + (selectedBrowser === browser.name ? 'text-nx-accent' : 'text-nx-text-secondary')} />
            <div>
              <div class="text-sm font-medium text-nx-text">{browser.name}</div>
              <div class="text-xs text-nx-text-muted">{browser.cookie_count} {t('cookies.cookies_label')}</div>
            </div>
          </div>
        </button>
      {/each}
    </div>

    {#if browsers.length === 0}
      <div class="mt-4 nx-card p-3 text-xs text-nx-text-secondary">
        {t('cookies.no_browsers')}
      </div>
    {/if}
  </div>

  <!-- Filter and Extract -->
  <div class="mb-6 nx-card p-5">
    <div class="flex items-end gap-3">
      <div class="flex-1">
        <label for="cookie-domain-filter" class="mb-1 block text-xs text-nx-text-muted">{t('cookies.domain_filter')}</label>
        <input
          id="cookie-domain-filter"
          type="text"
          bind:value={domainFilter}
          placeholder={t('cookies.filter_placeholder')}
          class="nx-input w-full"
        />
      </div>
      <button
        class="nx-btn nx-btn-primary px-6 py-2 disabled:opacity-50 disabled:cursor-not-allowed"
        onclick={extractCookies}
        disabled={!selectedBrowser || extracting}>
        {#if extracting}
          <span class="flex items-center gap-2">
            <span class="material-symbols-outlined nx-animate-spin text-lg">progress_activity</span>
            {t('cookies.extracting')}
          </span>
        {:else}
          <span class="flex items-center gap-2">
            <span class="material-symbols-outlined text-lg">download</span>
            {t('cookies.extract')}
          </span>
        {/if}
      </button>
    </div>
  </div>

  <!-- Results -->
  {#if cookies.length > 0}
    <!-- 显示上限提示 -->
    {#if cookies.length >= MAX_DISPLAY}
      <div class="border-b border-nx-border bg-amber-500/10 px-4 py-2 text-xs text-amber-600">
        仅显示前 {MAX_DISPLAY} 条 cookie，请使用域名过滤或导出功能获取完整数据。
      </div>
    {/if}
    <!-- Results -->
    <div class="nx-section">
      <!-- Toolbar -->
      <div class="nx-section-header flex items-center justify-between">
        <div class="text-sm text-nx-text">
          <span class="font-medium">{cookies.length}</span> {t('cookies.cookies_extracted')}
        </div>
        <div class="flex gap-2">
          <button
            class="nx-btn nx-btn-ghost px-3 py-1.5 text-xs"
            onclick={copyAllCookies}>
            {t('cookies.copy_all')}
          </button>
          <button
            class="nx-btn nx-btn-ghost px-3 py-1.5 text-xs"
            onclick={exportJSON}>
            {t('cookies.export_json')}
          </button>
          <button
            class="nx-btn nx-btn-ghost px-3 py-1.5 text-xs"
            onclick={exportNetscape}>
            {t('cookies.export_netscape')}
          </button>
        </div>
      </div>

      <!-- Cookie List -->
      <div class="max-h-96 overflow-y-auto">
        <table class="nx-table w-full">
          <thead class="sticky top-0 bg-nx-surface">
            <tr class="border-b border-nx-border text-xs text-nx-text-muted">
              <th class="px-4 py-2 text-left font-medium">{t('cookies.name')}</th>
              <th class="px-4 py-2 text-left font-medium">{t('cookies.value')}</th>
              <th class="px-4 py-2 text-left font-medium">{t('cookies.domain')}</th>
              <th class="px-4 py-2 text-left font-medium">{t('cookies.expires')}</th>
              <th class="px-4 py-2 text-right font-medium">{t('cookies.actions')}</th>
            </tr>
          </thead>
          <tbody>
            {#each cookies as cookie}
              <tr class="group border-b border-nx-border last:border-0">
                <td class="max-w-[200px] px-4 py-2">
                  <div class="truncate text-sm font-medium text-nx-text" title={cookie.name}>
                    {cookie.name}
                  </div>
                </td>
                <td class="max-w-[300px] px-4 py-2">
                  <div class="truncate font-mono text-xs text-nx-text-secondary" title={cookie.value}>
                    {cookie.value}
                  </div>
                </td>
                <td class="px-4 py-2 text-xs text-nx-text-muted">
                  {cookie.domain}
                </td>
                <td class="px-4 py-2 text-xs text-nx-text-muted">
                  {formatDate(cookie.expires)}
                </td>
                <td class="px-4 py-2">
                  <div class="flex items-center justify-end gap-1">
                    <button
                      class="p-1 text-nx-text-secondary"
                      title={t('cookies.copy_cookie')}
                      onclick={() => copyCookie(cookie)}>
                      <span class="material-symbols-outlined text-base">content_copy</span>
                    </button>
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </div>
  {:else if extracting === false && cookies.length === 0 && selectedBrowser}
    <div class="nx-empty p-12 text-center">
      <span class="material-symbols-outlined text-nx-text-muted text-4xl">cookie</span>
      <div class="mt-4 text-sm text-nx-text-muted">{t('cookies.no_cookies')}</div>
      <div class="mt-1 text-xs text-nx-text-muted">{t('cookies.extract_begin')}</div>
      <div class="mt-3 text-xs text-amber-600">{t('cookies.extract_hint')}</div>
    </div>
  {/if}
</div>
