// src/views/PasswordManager.vue
<script setup>
import { ref, onMounted } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { showToast } from "../lib/toast.js";
import { showConfirm } from "../lib/confirm.js";
import { t } from "../lib/i18n.js";
import { friendlyError } from "../lib/errors.js";
import VaultDialog from "../components/VaultDialog.vue";

const locked = ref(true);
const hasMasterPassword = ref(false);
const masterPassword = ref("");
const setupPassword = ref("");
const setupPasswordConfirm = ref("");
const passwords = ref([]);
const loading = ref(true);
const showAddModal = ref(false);
const showPassword = ref(null);

// 表单数据
const entryName = ref("");
const username = ref("");
const password = ref("");
const url = ref("");
const notes = ref("");

// 编辑表单
const showEditModal = ref(false);
const editId = ref(null);
const editName = ref("");
const editUsername = ref("");
const editPassword = ref("");
const editUrl = ref("");
const editNotes = ref("");

async function checkState() {
  try {
    const lockedState = await invoke("is_locked");
    const hasPwd = await invoke("has_master_password");
    locked.value = lockedState;
    hasMasterPassword.value = hasPwd;
  } catch (err) {
    console.error("Failed to check password manager state:", err);
    showToast(t("common.error_msg").replace("{error}", friendlyError(err)), "error");
  }
}

async function setupMasterPassword() {
  if (!setupPassword.value || setupPassword.value.length < 4) {
    showToast(t("common.master_too_short"));
    return;
  }
  if (setupPassword.value !== setupPasswordConfirm.value) {
    showToast(t("common.no_match"));
    return;
  }
  try {
    await invoke("set_master_password", { masterPassword: setupPassword.value });
    locked.value = false;
    hasMasterPassword.value = true;
    setupPassword.value = "";
    setupPasswordConfirm.value = "";
    await loadPasswords();
    showToast(t("common.master_set_ok"));
  } catch (err) {
    showToast(t("common.set_master_failed").replace("{error}", friendlyError(err)));
  }
}

async function unlock() {
  if (!masterPassword.value) return;
  try {
    const success = await invoke("unlock", { masterPassword: masterPassword.value });
    if (success) {
      locked.value = false;
      masterPassword.value = "";
      await loadPasswords();
      showToast(t("common.unlocked"));
    } else {
      showToast(t("common.incorrect"));
    }
  } catch (err) {
    showToast(t("common.unlock_failed").replace("{error}", friendlyError(err)));
  }
}

async function lockVault() {
  try {
    await invoke("lock");
    locked.value = true;
    passwords.value = [];
    showToast(t("common.locked"));
  } catch (err) {
    console.error("Failed to lock:", err);
  }
}

async function loadPasswords() {
  try {
    loading.value = true;
    passwords.value = await invoke("list_passwords");
  } catch (err) {
    console.error("Failed to load passwords:", err);
    showToast(t("passwords.failed_load"));
  } finally {
    loading.value = false;
  }
}

async function addPassword() {
  if (!entryName.value || !username.value || !password.value) {
    showToast(t("passwords.fill_fields"));
    return;
  }
  try {
    await invoke("add_password", {
      name: entryName.value,
      username: username.value,
      password: password.value,
      url: url.value || null,
      notes: notes.value || null,
    });
    showAddModal.value = false;
    resetForm();
    await loadPasswords();
    showToast(t("passwords.add_success"));
  } catch (err) {
    showToast(t("passwords.add_failed").replace("{error}", friendlyError(err)));
  }
}

async function deletePassword(id) {
  if (!(await showConfirm(t("passwords.delete_confirm")))) return;
  try {
    await invoke("delete_password", { id });
    await loadPasswords();
  } catch (err) {
    showToast(t("passwords.delete_failed").replace("{error}", friendlyError(err)));
  }
}

function beginEdit(entry) {
  editId.value = entry.id;
  editName.value = entry.name;
  editUsername.value = entry.username;
  editPassword.value = "";
  editUrl.value = entry.url || "";
  editNotes.value = entry.notes || "";
  showEditModal.value = true;
}

async function saveEdit() {
  if (!editName.value || !editUsername.value) {
    showToast(t("passwords.fill_fields"));
    return;
  }
  try {
    await invoke("update_password", {
      id: editId.value,
      name: editName.value,
      username: editUsername.value,
      password: editPassword.value.trim() ? editPassword.value.trim() : null,
      url: editUrl.value.trim() ? editUrl.value.trim() : null,
      notes: editNotes.value.trim() ? editNotes.value.trim() : null,
    });
    showEditModal.value = false;
    await loadPasswords();
    showToast(t("passwords.edit_success"));
  } catch (err) {
    showToast(t("passwords.edit_failed").replace("{error}", friendlyError(err)));
  }
}

async function viewPassword(id) {
  try {
    const pwd = await invoke("get_password", { id });
    showPassword.value = { id, password: pwd };
  } catch (err) {
    showToast(t("passwords.view_failed").replace("{error}", friendlyError(err)));
  }
}

async function exportCSV() {
  try {
    const csvContent = await invoke("export_chrome_csv");
    const blob = new Blob([csvContent], { type: "text/csv" });
    const downloadUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = downloadUrl;
    a.download = `passwords_export_${new Date().toISOString().split("T")[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(downloadUrl);
    showToast(t("passwords.export_success"));
  } catch (err) {
    showToast(t("passwords.export_failed").replace("{error}", friendlyError(err)));
  }
}

async function importCSV({ file }) {
  const raw = file?.originFile || file?.file || file;
  if (!raw) return;
  try {
    const text = await raw.text();
    const count = await invoke("import_chrome_csv", { csvContent: text });
    await loadPasswords();
    showToast(t("passwords.import_success").replace("{count}", count));
  } catch (err) {
    showToast(t("passwords.import_failed").replace("{error}", friendlyError(err)));
  }
}

async function saveToFile() {
  const fileMasterPwd = prompt(t("passwords.master_pwd_save"));
  if (!fileMasterPwd) return;
  try {
    const filePath = prompt(t("passwords.file_path_save"));
    if (!filePath) return;
    await invoke("save_to_file", { filePath, masterPassword: fileMasterPwd });
    showToast(t("passwords.save_success"));
  } catch (err) {
    showToast(t("passwords.save_failed").replace("{error}", friendlyError(err)));
  }
}

async function loadFromFile() {
  const fileMasterPwd = prompt(t("passwords.master_pwd_load"));
  if (!fileMasterPwd) return;
  try {
    const filePath = prompt(t("passwords.file_path_load"));
    if (!filePath) return;
    const count = await invoke("load_from_file", { filePath, masterPassword: fileMasterPwd });
    await loadPasswords();
    showToast(t("passwords.load_success").replace("{count}", count));
  } catch (err) {
    showToast(t("passwords.load_failed").replace("{error}", friendlyError(err)));
  }
}

function resetForm() {
  entryName.value = "";
  username.value = "";
  password.value = "";
  url.value = "";
  notes.value = "";
}

function copyToClipboard(text) {
  navigator.clipboard
    .writeText(text)
    .then(() => {
      showToast(t("passwords.copied"));
    })
    .catch(() => {
      showToast(t("common.copy_failed"), "error");
    });
}

const addGroups = [
  [
    { id: "pm-name-add", labelKey: "passwords.name", required: true, value: entryName, onInput: (v) => (entryName.value = v), placeholder: "GitHub Account" },
    { id: "pm-username-add", labelKey: "passwords.username", required: true, value: username, onInput: (v) => (username.value = v), placeholder: "user@example.com" },
  ],
  [
    { id: "pm-password-add", labelKey: "passwords.password", required: true, type: "password", value: password, onInput: (v) => (password.value = v), placeholder: "••••••••" },
    { id: "pm-url-add", labelKey: "URL", type: "url", value: url, onInput: (v) => (url.value = v), placeholder: "https://github.com" },
  ],
  [
    { id: "pm-notes-add", labelKey: "passwords.notes", textarea: true, value: notes, onInput: (v) => (notes.value = v), placeholder: "Additional information..." },
  ],
];

const editGroups = [
  [
    { id: "pm-name-edit", labelKey: "passwords.name", required: true, value: editName, onInput: (v) => (editName.value = v) },
    { id: "pm-username-edit", labelKey: "passwords.username", required: true, value: editUsername, onInput: (v) => (editUsername.value = v) },
  ],
  [
    { id: "pm-password-edit", labelKey: "passwords.password", type: "password", value: editPassword, onInput: (v) => (editPassword.value = v), placeholder: t("passwords.keep_password") },
    { id: "pm-url-edit", labelKey: "URL", type: "url", value: editUrl, onInput: (v) => (editUrl.value = v) },
  ],
  [
    { id: "pm-notes-edit", labelKey: "passwords.notes", textarea: true, value: editNotes, onInput: (v) => (editNotes.value = v) },
  ],
];

onMounted(async () => {
  await checkState();
  if (!locked.value) {
    await loadPasswords();
  } else {
    loading.value = false;
  }
});
</script>

<template>
  <div class="page pm-page">
    <!-- Header -->
    <div class="page-header">
      <div>
        <h1 class="page-title">{{ t("passwords.title") }}</h1>
        <p class="page-desc">{{ t("passwords.desc") }}</p>
      </div>
      <div v-if="!locked" class="flex gap-2 items-center">
        <a-button @click="exportCSV">
          <template #icon><icon-download /></template>
          {{ t("passwords.export_csv") }}
        </a-button>
        <a-upload :show-file-list="false" :auto-upload="false" accept=".csv" @change="importCSV">
          <a-button>
            <template #icon><icon-upload /></template>
            {{ t("passwords.import_csv") }}
          </a-button>
        </a-upload>
        <a-button @click="saveToFile">
          <template #icon><icon-save /></template>
          {{ t("passwords.save_encrypted") }}
        </a-button>
        <a-button type="primary" @click="showAddModal = true">
          <template #icon><icon-plus /></template>
          {{ t("passwords.add") }}
        </a-button>
        <a-button status="danger" @click="lockVault">
          <template #icon><icon-lock /></template>
          {{ t("passwords.lock") }}
        </a-button>
      </div>
    </div>

    <!-- Lock/Setup Screen -->
    <div v-if="locked" class="lock-screen">
      <!-- Unlock -->
      <a-card v-if="hasMasterPassword" :bordered="true" class="lock-card">
        <div class="lock-icon"><icon-lock /></div>
        <h2 class="lock-title">{{ t("passwords.title_locked") }}</h2>
        <p class="lock-desc">{{ t("passwords.desc_locked") }}</p>
        <a-input-password
          v-model="masterPassword"
          :placeholder="t('passwords.master_password_placeholder')"
          size="large"
          class="lock-input"
          @press-enter="unlock"
        />
        <a-button type="primary" long size="large" :disabled="!masterPassword" @click="unlock">
          {{ t("passwords.unlock") }}
        </a-button>
      </a-card>

      <!-- Setup Master Password -->
      <a-card v-else :bordered="true" class="lock-card">
        <div class="lock-icon"><icon-lock /></div>
        <h2 class="lock-title">{{ t("passwords.title_setup") }}</h2>
        <p class="lock-desc">{{ t("passwords.desc_setup") }}</p>
        <a-input-password
          v-model="setupPassword"
          :placeholder="t('passwords.setup_password_placeholder')"
          size="large"
          class="lock-input"
        />
        <a-input-password
          v-model="setupPasswordConfirm"
          :placeholder="t('passwords.setup_password_confirm_placeholder')"
          size="large"
          class="lock-input"
          @press-enter="setupMasterPassword"
        />
        <a-button
          type="primary"
          long
          size="large"
          :disabled="!setupPassword || !setupPasswordConfirm"
          @click="setupMasterPassword"
        >
          {{ t("passwords.setup") }}
        </a-button>
      </a-card>
    </div>

    <a-spin v-else-if="loading" style="display: flex; justify-content: center; padding: 56px 0" />

    <a-empty
      v-else-if="passwords.length === 0"
      style="padding: 56px 0"
      :description="t('passwords.no_passwords')"
    >
      <template #description>
        <div>{{ t("passwords.no_passwords") }}</div>
        <div class="empty-hint">{{ t("passwords.no_passwords_desc") }}</div>
      </template>
    </a-empty>

    <a-card v-else :bordered="true">
      <a-table :data="passwords" :pagination="false" :row-key="'id'" :bordered="false" size="small">
        <template #columns>
          <a-table-column :title="t('passwords.name')">
            <template #cell="{ record }">
              <div class="name-cell">
                <icon-lock class="name-icon" />
                <span class="name-text">{{ record.name }}</span>
              </div>
            </template>
          </a-table-column>
          <a-table-column :title="t('passwords.username')" data-index="username">
            <template #cell="{ record }">
              <span class="username">{{ record.username }}</span>
            </template>
          </a-table-column>
          <a-table-column title="URL">
            <template #cell="{ record }">
              <a-link v-if="record.url" :href="record.url" target="_blank" class="url-link">
                {{ record.url }}
              </a-link>
              <span v-else class="muted">{{ t("passwords.no_url") }}</span>
            </template>
          </a-table-column>
          <a-table-column :title="t('passwords.created')" data-index="created_at">
            <template #cell="{ record }">
              <span class="muted">{{ record.created_at }}</span>
            </template>
          </a-table-column>
          <a-table-column :title="t('passwords.actions')" align="right" :width="190">
            <template #cell="{ record }">
              <div class="actions">
                <a-tooltip :content="t('passwords.title_view')">
                  <a-button type="text" size="mini" @click="viewPassword(record.id)">
                    <template #icon><icon-eye /></template>
                  </a-button>
                </a-tooltip>
                <a-tooltip :content="t('passwords.title_edit')">
                  <a-button type="text" size="mini" @click="beginEdit(record)">
                    <template #icon><icon-edit /></template>
                  </a-button>
                </a-tooltip>
                <a-tooltip :content="t('passwords.title_copy')">
                  <a-button type="text" size="mini" @click="copyToClipboard(record.username)">
                    <template #icon><icon-copy /></template>
                  </a-button>
                </a-tooltip>
                <a-tooltip :content="t('passwords.title_delete')">
                  <a-button type="text" size="mini" status="danger" @click="deletePassword(record.id)">
                    <template #icon><icon-delete /></template>
                  </a-button>
                </a-tooltip>
              </div>
            </template>
          </a-table-column>
        </template>
      </a-table>
    </a-card>

    <!-- Add Password Modal -->
    <VaultDialog
      v-if="showAddModal"
      :title="t('passwords.add')"
      :groups="addGroups"
      :submit-label="t('passwords.save')"
      @submit="addPassword"
      @close="showAddModal = false"
    />

    <!-- Edit Password Modal -->
    <VaultDialog
      v-if="showEditModal"
      :title="t('passwords.edit_title')"
      :groups="editGroups"
      :submit-label="t('passwords.save')"
      @submit="saveEdit"
      @close="showEditModal = false"
    />

    <!-- View Password Modal -->
    <VaultDialog
      v-if="showPassword"
      mode="view"
      :title="t('passwords.details')"
      :password="showPassword.password"
      @copy="copyToClipboard(showPassword.password)"
      @close="showPassword = null"
    />
  </div>
</template>

<style scoped>
.empty-hint {
  font-size: 12px;
  color: var(--color-text-3);
  margin-top: 4px;
}
.lock-screen {
  display: flex;
  justify-content: center;
  margin-top: 48px;
}
.lock-card {
  width: 100%;
  max-width: 420px;
  padding: 24px 8px;
  text-align: center;
  border-radius: 12px;
}
.lock-icon {
  font-size: 44px;
  color: var(--color-text-2);
  margin-bottom: 12px;
}
.lock-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--color-text-1);
  margin: 0 0 4px;
}
.lock-desc {
  font-size: 13px;
  color: var(--color-text-3);
  margin: 0 0 20px;
}
.lock-input {
  margin-bottom: 12px;
}
.name-cell {
  display: flex;
  align-items: center;
  gap: 8px;
}
.name-icon {
  color: var(--color-text-2);
}
.name-text {
  font-weight: 500;
  color: var(--color-text-1);
}
.username {
  color: var(--color-text-2);
  font-size: 13px;
}
.url-link {
  font-size: 12px;
}
.muted {
  color: var(--color-text-3);
  font-size: 12px;
}
.actions {
  display: flex;
  justify-content: flex-end;
  gap: 2px;
}
</style>

// src/routes/PasswordManager.svelte
<script>
import { invoke } from "@tauri-apps/api/core";
  import { onMount } from "svelte";
  import { showToast } from "../lib/toast.svelte.js";
  import { showConfirm } from "../lib/confirm.svelte.js";
  import { t } from "../lib/i18n.svelte.js";
  import { friendlyError } from "../lib/errors.svelte.js";
  import VaultDialog from "../components/VaultDialog.svelte";

  let locked = $state(true);
  let hasMasterPassword = $state(false);
  let masterPassword = $state("");
  let setupPassword = $state("");
  let setupPasswordConfirm = $state("");
  let passwords = $state([]);
  let loading = $state(true);
  let showAddModal = $state(false);
  let showPassword = $state(null);
  
  // 表单数据
  let entryName = $state("");
  let username = $state("");
  let password = $state("");
  let url = $state("");
  let notes = $state("");

  // 编辑表单
  let showEditModal = $state(false);
  let editId = $state(null);
  let editName = $state("");
  let editUsername = $state("");
  let editPassword = $state("");
  let editUrl = $state("");
  let editNotes = $state("");

  async function checkState() {
    try {
      const lockedState = await invoke("is_locked");
      const hasPwd = await invoke("has_master_password");
      locked = lockedState;
      hasMasterPassword = hasPwd;
    } catch (err) {
      console.error("Failed to check password manager state:", err);
      showToast(t('common.error_msg').replace('{error}', friendlyError(err)), "error");
    }
  }

  async function setupMasterPassword() {
    if (!setupPassword || setupPassword.length < 4) {
      showToast(t('common.master_too_short'));
      return;
    }
    if (setupPassword !== setupPasswordConfirm) {
      showToast(t('common.no_match'));
      return;
    }

    try {
      await invoke("set_master_password", { masterPassword: setupPassword });
      locked = false;
      hasMasterPassword = true;
      setupPassword = "";
      setupPasswordConfirm = "";
      await loadPasswords();
      showToast(t('common.master_set_ok'));
    } catch (err) {
      showToast(t('common.set_master_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function unlock() {
    if (!masterPassword) return;

    try {
      const success = await invoke("unlock", { masterPassword });
      if (success) {
        locked = false;
        masterPassword = "";
        await loadPasswords();
        showToast(t('common.unlocked'));
      } else {
        showToast(t('common.incorrect'));
      }
    } catch (err) {
      showToast(t('common.unlock_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function lockVault() {
    try {
      await invoke("lock");
      locked = true;
      passwords = [];
      showToast(t('common.locked'));
    } catch (err) {
      console.error("Failed to lock:", err);
    }
  }

  async function loadPasswords() {
    try {
      loading = true;
      passwords = await invoke("list_passwords");
    } catch (err) {
      console.error("Failed to load passwords:", err);
      showToast(t('passwords.failed_load'));
    } finally {
      loading = false;
    }
  }

  async function addPassword() {
    if (!entryName || !username || !password) {
      showToast(t('passwords.fill_fields'));
      return;
    }

    try {
      await invoke("add_password", {
        name: entryName,
        username,
        password,
        url: url || null,
        notes: notes || null,
      });
      
      showAddModal = false;
      resetForm();
      await loadPasswords();
      showToast(t('passwords.add_success'));
    } catch (err) {
      showToast(t('passwords.add_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function deletePassword(id) {
    if (!await showConfirm(t('passwords.delete_confirm'))) return;
    
    try {
      await invoke("delete_password", { id });
      await loadPasswords();
    } catch (err) {
      showToast(t('passwords.delete_failed').replace('{error}', friendlyError(err)));
    }
  }

  function beginEdit(entry) {
    editId = entry.id;
    editName = entry.name;
    editUsername = entry.username;
    editPassword = "";
    editUrl = entry.url || "";
    editNotes = entry.notes || "";
    showEditModal = true;
  }

  async function saveEdit() {
    if (!editName || !editUsername) {
      showToast(t('passwords.fill_fields'));
      return;
    }
    try {
      await invoke("update_password", {
        id: editId,
        name: editName,
        username: editUsername,
        password: editPassword.trim() ? editPassword.trim() : null,
        url: editUrl.trim() ? editUrl.trim() : null,
        notes: editNotes.trim() ? editNotes.trim() : null,
      });
      showEditModal = false;
      await loadPasswords();
      showToast(t('passwords.edit_success'));
    } catch (err) {
      showToast(t('passwords.edit_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function viewPassword(id) {
    try {
      const pwd = await invoke("get_password", { id });
      showPassword = { id, password: pwd };
    } catch (err) {
      showToast(t('passwords.view_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function exportCSV() {
    try {
      const csvContent = await invoke("export_chrome_csv");
      
      // 创建下载
      const blob = new Blob([csvContent], { type: 'text/csv' });
      const downloadUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = downloadUrl;
      a.download = `passwords_export_${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(downloadUrl);
      
      showToast(t('passwords.export_success'));
    } catch (err) {
      showToast(t('passwords.export_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function importCSV(event) {
    const file = event.target.files[0];
    if (!file) return;

    try {
      const text = await file.text();
      const count = await invoke("import_chrome_csv", { csvContent: text });
      await loadPasswords();
      showToast(t('passwords.import_success').replace('{count}', count));
      event.target.value = ''; // 重置文件输入
    } catch (err) {
      showToast(t('passwords.import_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function saveToFile() {
    const fileMasterPwd = prompt(t('passwords.master_pwd_save'));
    if (!fileMasterPwd) return;

    try {
      const filePath = prompt(t('passwords.file_path_save'));
      if (!filePath) return;

      await invoke("save_to_file", {
        filePath,
        masterPassword: fileMasterPwd,
      });
      showToast(t('passwords.save_success'));
    } catch (err) {
      showToast(t('passwords.save_failed').replace('{error}', friendlyError(err)));
    }
  }

  async function loadFromFile() {
    const fileMasterPwd = prompt(t('passwords.master_pwd_load'));
    if (!fileMasterPwd) return;

    try {
      const filePath = prompt(t('passwords.file_path_load'));
      if (!filePath) return;

      const count = await invoke("load_from_file", {
        filePath,
        masterPassword: fileMasterPwd,
      });
      await loadPasswords();
      showToast(t('passwords.load_success').replace('{count}', count));
    } catch (err) {
      showToast(t('passwords.load_failed').replace('{error}', friendlyError(err)));
    }
  }

  function resetForm() {
    entryName = "";
    username = "";
    password = "";
    url = "";
    notes = "";
  }

  function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(() => {
      showToast(t('passwords.copied'));
    }).catch(() => {
      showToast(t('common.copy_failed'), "error");
    });
  }

  // 新增 / 编辑弹窗字段配置
  let addGroups = $derived([
    [
      { id: "pm-name-add", labelKey: "passwords.name", required: true, value: entryName, onInput: (v) => entryName = v, placeholder: "GitHub Account" },
      { id: "pm-username-add", labelKey: "passwords.username", required: true, value: username, onInput: (v) => username = v, placeholder: "user@example.com" },
    ],
    [
      { id: "pm-password-add", labelKey: "passwords.password", required: true, type: "password", value: password, onInput: (v) => password = v, placeholder: "••••••••" },
      { id: "pm-url-add", labelKey: "URL", type: "url", value: url, onInput: (v) => url = v, placeholder: "https://github.com" },
    ],
    [
      { id: "pm-notes-add", labelKey: "passwords.notes", textarea: true, value: notes, onInput: (v) => notes = v, placeholder: "Additional information..." },
    ],
  ]);
  let editGroups = $derived([
    [
      { id: "pm-name-edit", labelKey: "passwords.name", required: true, value: editName, onInput: (v) => editName = v },
      { id: "pm-username-edit", labelKey: "passwords.username", required: true, value: editUsername, onInput: (v) => editUsername = v },
    ],
    [
      { id: "pm-password-edit", labelKey: "passwords.password", type: "password", value: editPassword, onInput: (v) => editPassword = v, placeholder: t('passwords.keep_password') },
      { id: "pm-url-edit", labelKey: "URL", type: "url", value: editUrl, onInput: (v) => editUrl = v },
    ],
    [
      { id: "pm-notes-edit", labelKey: "passwords.notes", textarea: true, value: editNotes, onInput: (v) => editNotes = v },
    ],
  ]);

  onMount(async () => {
    await checkState();
    if (!locked) {
      await loadPasswords();
    } else {
      loading = false;
    }
  });
</script>

<div class="mx-auto max-w-6xl p-5">
  <!-- Header -->
  <div class="mb-6 flex items-center justify-between">
    <div>
      <h1 class="text-xl font-semibold text-nx-text">{t('passwords.title')}</h1>
      <p class="mt-1 text-xs text-nx-text-muted">{t('passwords.desc')}</p>
    </div>
    <div class="flex gap-2">
      {#if locked}
        <span></span>
      {:else}
        <button 
          class="nx-btn nx-btn-ghost flex items-center gap-2"
          onclick={exportCSV}>
          <span class="material-symbols-outlined text-lg">download</span>
          {t('passwords.export_csv')}
        </button>
        <label class="nx-btn nx-btn-ghost flex cursor-pointer items-center gap-2">
          <span class="material-symbols-outlined text-lg">upload</span>
          {t('passwords.import_csv')}
          <input type="file" accept=".csv" class="hidden" onchange={importCSV} />
        </label>
        <button 
          class="nx-btn nx-btn-ghost flex items-center gap-2"
          onclick={saveToFile}>
          <span class="material-symbols-outlined text-lg">save</span>
          {t('passwords.save_encrypted')}
        </button>
        <button 
          class="nx-btn nx-btn-primary flex items-center gap-2"
          onclick={() => showAddModal = true}>
          <span class="material-symbols-outlined text-lg">add</span>
          {t('passwords.add')}
        </button>
        <button 
          class="nx-btn nx-btn-ghost flex items-center gap-2"
          onclick={lockVault}>
          <span class="material-symbols-outlined text-lg">lock</span>
          {t('passwords.lock')}
        </button>
      {/if}
    </div>
  </div>

  <!-- Lock/Setup Screen -->
  {#if locked}
    {#if hasMasterPassword}
      <!-- Unlock -->
      <div class="mx-auto mt-16 max-w-md nx-card p-8 text-center">
        <div class="mb-4">
          <span class="material-symbols-outlined text-nx-text-secondary text-5xl">lock</span>
        </div>
        <h2 class="mb-2 text-lg font-semibold text-nx-text">{t('passwords.title_locked')}</h2>
        <p class="mb-6 text-sm text-nx-text-muted">{t('passwords.desc_locked')}</p>
        <input
          type="password"
          bind:value={masterPassword}
          placeholder={t('passwords.master_password_placeholder')}
          class="nx-input mb-4 w-full"
          onkeydown={(e) => e.key === 'Enter' && unlock()}
        />
        <button
          class="nx-btn nx-btn-primary w-full"
          onclick={unlock}
          disabled={!masterPassword}>
          {t('passwords.unlock')}
        </button>
      </div>
    {:else}
      <!-- Setup Master Password -->
      <div class="mx-auto mt-16 max-w-md nx-card p-8 text-center">
        <div class="mb-4">
          <span class="material-symbols-outlined text-nx-text-secondary text-5xl">lock_reset</span>
        </div>
        <h2 class="mb-2 text-lg font-semibold text-nx-text">{t('passwords.title_setup')}</h2>
        <p class="mb-6 text-sm text-nx-text-muted">{t('passwords.desc_setup')}</p>
        <input
          type="password"
          bind:value={setupPassword}
          placeholder={t('passwords.setup_password_placeholder')}
          class="nx-input mb-3 w-full"
        />
        <input
          type="password"
          bind:value={setupPasswordConfirm}
          placeholder={t('passwords.setup_password_confirm_placeholder')}
          class="nx-input mb-4 w-full"
          onkeydown={(e) => e.key === 'Enter' && setupMasterPassword()}
        />
        <button
          class="nx-btn nx-btn-primary w-full"
          onclick={setupMasterPassword}
          disabled={!setupPassword || !setupPasswordConfirm}>
          {t('passwords.setup')}
        </button>
      </div>
    {/if}
  {:else if loading}
    <div class="flex items-center justify-center py-12">
      <span class="material-symbols-outlined nx-animate-spin text-nx-text-muted text-3xl">progress_activity</span>
    </div>
  {:else if passwords.length === 0}
    <div class="nx-empty p-12 text-center">
      <span class="material-symbols-outlined text-nx-text-muted text-4xl">lock</span>
      <div class="mt-4 text-sm text-nx-text-muted">{t('passwords.no_passwords')}</div>
      <div class="mt-1 text-xs text-nx-text-muted">{t('passwords.no_passwords_desc')}</div>
    </div>
  {:else}
    <div class="nx-section">
      <table class="nx-table w-full">
        <thead>
          <tr class="border-b border-nx-border text-xs text-nx-text-muted">
            <th class="px-4 py-3 text-left font-medium">{t('passwords.name')}</th>
            <th class="px-4 py-3 text-left font-medium">{t('passwords.username')}</th>
            <th class="px-4 py-3 text-left font-medium">URL</th>
            <th class="px-4 py-3 text-left font-medium">{t('passwords.created')}</th>
            <th class="px-4 py-3 text-right font-medium">{t('passwords.actions')}</th>
          </tr>
        </thead>
        <tbody>
          {#each passwords as entry (entry.id)}
            <tr class="group border-b border-nx-border last:border-0">
              <td class="px-4 py-3">
                <div class="flex items-center gap-2">
                  <span class="material-symbols-outlined text-nx-text-secondary">key</span>
                  <span class="text-sm font-medium text-nx-text">{entry.name}</span>
                </div>
              </td>
              <td class="px-4 py-3 text-sm text-nx-text-secondary">{entry.username}</td>
              <td class="px-4 py-3 text-xs text-nx-text-muted">
                {#if entry.url}
                  <a href={entry.url} target="_blank" class="text-nx-text-secondary underline">{entry.url}</a>
                {:else}
                  <span class="text-nx-text-muted">{t('passwords.no_url')}</span>
                {/if}
              </td>
              <td class="px-4 py-3 text-xs text-nx-text-muted">{entry.created_at}</td>
              <td class="px-4 py-3">
                <div class="flex items-center justify-end gap-1">
                  <button 
                    class="p-1.5 text-nx-text-secondary"
                    title={t('passwords.title_view')}
                    onclick={() => viewPassword(entry.id)}>
                    <span class="material-symbols-outlined text-lg">visibility</span>
                  </button>
                  <button 
                    class="p-1.5 text-nx-text-secondary"
                    title={t('passwords.title_edit')}
                    onclick={() => beginEdit(entry)}>
                    <span class="material-symbols-outlined text-lg">edit</span>
                  </button>
                  <button 
                    class="p-1.5 text-nx-text-secondary"
                    title={t('passwords.title_copy')}
                    onclick={() => copyToClipboard(entry.username)}>
                    <span class="material-symbols-outlined text-lg">content_copy</span>
                  </button>
                  <button 
                    class="p-1.5 text-nx-text-secondary"
                    title={t('passwords.title_delete')}
                    onclick={() => deletePassword(entry.id)}>
                    <span class="material-symbols-outlined text-lg">delete</span>
                  </button>
                </div>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>

<!-- Add Password Modal -->
{#if showAddModal}
  <VaultDialog title={t('passwords.add')} groups={addGroups} submitLabel={t('passwords.save')} onSubmit={addPassword} onClose={() => showAddModal = false} />
{/if}

<!-- Edit Password Modal -->
{#if showEditModal}
  <VaultDialog title={t('passwords.edit_title')} groups={editGroups} submitLabel={t('passwords.save')} onSubmit={saveEdit} onClose={() => showEditModal = false} />
{/if}

<!-- View Password Modal -->
{#if showPassword}
  <VaultDialog mode="view" title={t('passwords.details')} password={showPassword.password} onCopy={() => copyToClipboard(showPassword.password)} onClose={() => showPassword = null} />
{/if}
