// src/components/containers/ComposeTab.vue
<script setup>
import { computed } from "vue";
import { t } from "../../lib/i18n.js";
import ContainerIcons from "../../icons/ContainerIcons.vue";

const props = defineProps({
  file: { type: String, default: "" },
  project: { type: String, default: "" },
  loading: { type: Boolean, default: false },
  error: { type: String, default: null },
  containers: { type: Array, default: () => [] },
  logs: { type: String, default: "" },
});

const emit = defineEmits([
  "file-input",
  "project-input",
  "up",
  "down",
  "ps",
  "logs",
  "clear-logs",
]);

function statusLabel(status) {
  const map = {
    running: t("docker.status_running"),
    exited: t("docker.status_exited"),
    paused: t("docker.status_paused"),
    created: t("docker.status_created"),
  };
  return map[status] || status;
}

const columns = computed(() => [
  { title: t("docker.name"), slotName: "name" },
  { title: t("docker.image"), slotName: "image" },
  { title: t("docker.status"), slotName: "status" },
  { title: t("docker.ports"), slotName: "ports" },
]);
</script>

<template>
  <div>
    <div class="grid grid-cols-2 gap-3 mb-4">
      <div>
        <label class="field-label">{{ t("docker.compose_file") }}</label>
        <a-input
          :model-value="file"
          placeholder="docker-compose.yml"
          @input="(v) => emit('file-input', v)"
        />
      </div>
      <div>
        <label class="field-label">{{ t("docker.compose_project") }}</label>
        <a-input
          :model-value="project"
          :placeholder="t('docker.compose_project_ph')"
          @input="(v) => emit('project-input', v)"
        />
      </div>
    </div>

    <div class="flex items-center gap-2 mb-4">
      <a-button type="primary" status="success" size="small" :disabled="loading" @click="emit('up')">
        <template #icon><icon-play-arrow /></template>
        {{ t("docker.compose_up") }}
      </a-button>
      <a-button status="danger" size="small" :disabled="loading" @click="emit('down')">
        <template #icon><icon-stop /></template>
        {{ t("docker.compose_down") }}
      </a-button>
      <a-button size="small" :disabled="loading" @click="emit('ps')">
        <template #icon><icon-menu /></template>
        {{ t("docker.compose_ps") }}
      </a-button>
      <a-button size="small" :disabled="loading" @click="emit('logs')">
        <template #icon><icon-file /></template>
        {{ t("docker.compose_logs") }}
      </a-button>
    </div>

    <a-alert v-if="error" type="error" class="mb-4">
      <pre class="error-pre">{{ error }}</pre>
    </a-alert>

    <a-card v-if="containers.length > 0" :bordered="true" class="section-card mb-4">
      <template #title>
        <span class="section-title">{{ t("docker.compose_services") }}</span>
      </template>
      <a-table
        :data="containers"
        :columns="columns"
        :pagination="false"
        :bordered="{ wrapper: false, cell: false }"
        size="small"
      >
        <template #name="{ record }">
          <span class="cell-name">{{ record.name }}</span>
        </template>
        <template #image="{ record }">
          <span class="cell-mono">{{ record.image }}</span>
        </template>
        <template #status="{ record }">
          <span class="status-inline" :class="record.status === 'running' ? 'ok' : ''">
            <ContainerIcons
              :name="record.status === 'running' ? 'container-running' : 'container-exited'"
              :size="12"
            />
            {{ statusLabel(record.status) }}
          </span>
        </template>
        <template #ports="{ record }">
          <span class="cell-mono cell-muted">{{ record.ports || "-" }}</span>
        </template>
      </a-table>
    </a-card>

    <a-card v-if="logs" :bordered="true" class="section-card">
      <template #title>
        <div class="card-title-row">
          <span class="section-title">{{ t("docker.logs") }}</span>
          <a-button size="mini" @click="emit('clear-logs')">
            <template #icon><icon-close /></template>
          </a-button>
        </div>
      </template>
      <pre class="logs-pre">{{ logs }}</pre>
    </a-card>
  </div>
</template>

<style scoped>
.grid-cols-2 {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}
.field-label {
  display: block;
  margin-bottom: 6px;
  font-size: 12px;
  color: var(--color-text-3);
}
.section-card {
  border-radius: 10px;
}
.section-title {
  font-size: 12px;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--color-text-3);
}
.card-title-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}
.error-pre {
  margin: 0;
  font-family: "JetBrains Mono", monospace;
  font-size: 12px;
  white-space: pre-wrap;
  color: rgb(var(--red-6));
}
.cell-name {
  font-weight: 500;
  color: var(--color-text-1);
}
.cell-mono {
  font-family: "JetBrains Mono", monospace;
  font-size: 12px;
  color: var(--color-text-2);
}
.cell-muted {
  color: var(--color-text-3);
}
.status-inline {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  color: var(--color-text-3);
}
.status-inline.ok {
  color: rgb(var(--green-6));
}
.logs-pre {
  margin: 0;
  max-height: 400px;
  overflow: auto;
  padding: 12px 0;
  font-family: "JetBrains Mono", monospace;
  font-size: 12px;
  color: var(--color-text-2);
  white-space: pre-wrap;
}
</style>

// src/components/containers/ComposeTab.svelte
<script>
  import { t } from "../../lib/i18n.svelte.js";
  import ContainerIcons from "../../icons/ContainerIcons.svelte";

  let {
    file = "",
    project = "",
    loading = false,
    error = null,
    containers = [],
    logs = "",
    onFileInput,
    onProjectInput,
    onUp,
    onDown,
    onPs,
    onLogs,
    onClearLogs,
  } = $props();

  function statusLabel(status) {
    const map = {
      running: t("docker.status_running"), exited: t("docker.status_exited"),
      paused: t("docker.status_paused"), created: t("docker.status_created"),
    };
    return map[status] || status;
  }
</script>

<div>
  <div class="mb-4 grid grid-cols-2 gap-3">
    <div>
      <label for="compose-file" class="mb-1.5 block text-xs text-nx-text-muted">{t("docker.compose_file")}</label>
      <input id="compose-file" type="text" value={file} oninput={(e) => onFileInput(e.currentTarget.value)} placeholder="docker-compose.yml"
        class="nx-input w-full h-9 text-sm" />
    </div>
    <div>
      <label for="compose-project" class="mb-1.5 block text-xs text-nx-text-muted">{t("docker.compose_project")}</label>
      <input id="compose-project" type="text" value={project} oninput={(e) => onProjectInput(e.currentTarget.value)} placeholder={t("docker.compose_project_ph")}
        class="nx-input w-full h-9 text-sm" />
    </div>
  </div>

  <div class="mb-4 flex items-center gap-2">
    <button class="nx-btn text-xs h-8 text-nx-success" onclick={onUp} disabled={loading}>
      <span class="material-symbols-outlined text-sm">play_arrow</span>{t("docker.compose_up")}
    </button>
    <button class="nx-btn text-xs h-8 text-nx-danger" onclick={onDown} disabled={loading}>
      <span class="material-symbols-outlined text-sm">stop</span>{t("docker.compose_down")}
    </button>
    <button class="nx-btn text-xs h-8" onclick={onPs} disabled={loading}>
      <span class="material-symbols-outlined text-sm">list</span>{t("docker.compose_ps")}
    </button>
    <button class="nx-btn text-xs h-8" onclick={onLogs} disabled={loading}>
      <span class="material-symbols-outlined text-sm">list_alt</span>{t("docker.compose_logs")}
    </button>
  </div>

  {#if error}
    <div class="mb-4 nx-section">
      <div class="nx-section-body">
        <pre class="font-mono text-xs text-nx-danger whitespace-pre-wrap">{error}</pre>
      </div>
    </div>
  {/if}

  {#if containers.length > 0}
    <div class="mb-4 nx-section">
      <div class="nx-section-header">
        <span class="text-xs font-medium uppercase tracking-wider text-nx-text-muted">{t("docker.compose_services")}</span>
      </div>
      <table class="nx-table">
        <thead>
          <tr>
            <th>{t("docker.name")}</th>
            <th>{t("docker.image")}</th>
            <th>{t("docker.status")}</th>
            <th>{t("docker.ports")}</th>
          </tr>
        </thead>
        <tbody>
          {#each containers as c}
            <tr>
              <td class="text-sm text-nx-text">{c.name}</td>
              <td class="font-mono text-xs text-nx-text-secondary">{c.image}</td>
              <td>
                <span class="inline-flex items-center gap-1 text-xs {c.status === 'running' ? 'text-nx-success' : 'text-nx-text-muted'}">
                  <ContainerIcons name={c.status === 'running' ? 'container-running' : 'container-exited'} size={12} />
                  {statusLabel(c.status)}
                </span>
              </td>
              <td class="font-mono text-xs text-nx-text-muted">{c.ports || "-"}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}

  {#if logs}
    <div class="nx-section">
      <div class="nx-section-header">
        <span class="text-xs font-medium uppercase tracking-wider text-nx-text-muted">{t("docker.logs")}</span>
        <button class="text-nx-text-muted hover:text-nx-text" onclick={onClearLogs}>
          <span class="material-symbols-outlined text-sm">close</span>
        </button>
      </div>
      <pre class="max-h-[400px] overflow-auto p-4 font-mono text-xs text-nx-text-secondary whitespace-pre-wrap">{logs}</pre>
    </div>
  {/if}
</div>
