// src/components/containers/ContainerDialog.vue
<script setup>
import { t } from "../../lib/i18n.js";

/**
 * config: {
 *   title, icon, width,
 *   fields: [{ id, type, placeholder, value, onInput, enterSubmit }],
 *   loading, submitLabel, loadingLabel, canSubmit,
 *   onSubmit, onClose,
 * }
 */
const props = defineProps({
  config: { type: Object, required: true },
});
</script>

<template>
  <a-modal
    :visible="true"
    :title="config.title"
    :width="config.width || 400"
    :footer="false"
    :closable="false"
    :mask-closable="false"
    @cancel="config.onClose"
  >
    <template #title>
      <span class="dialog-title">
        <icon-edit v-if="config.icon === 'edit'" />
        <icon-download v-else-if="config.icon === 'download'" />
        <icon-build v-else-if="config.icon === 'construction'" />
        <icon-upload v-else-if="config.icon === 'upload'" />
        <icon-tags v-else-if="config.icon === 'sell'" />
        <icon-plus v-else-if="config.icon === 'add'" />
        <span>{{ config.title }}</span>
      </span>
    </template>

    <div class="dialog-body" :class="{ 'multi-field': config.fields.length > 1 }">
      <a-input
        v-for="f in config.fields"
        :key="f.id"
        :id="f.id"
        :type="f.type || 'text'"
        :model-value="f.value"
        :placeholder="f.placeholder"
        @input="(v) => f.onInput(v)"
        @press-enter="f.enterSubmit !== false && config.onSubmit()"
      />
    </div>

    <template #footer>
      <div class="dialog-footer">
        <a-button @click="config.onClose">{{ t("common.cancel") }}</a-button>
        <a-button
          type="primary"
          :loading="config.loading"
          :disabled="!config.canSubmit"
          @click="config.onSubmit"
        >
          {{ config.loading ? config.loadingLabel : config.submitLabel }}
        </a-button>
      </div>
    </template>
  </a-modal>
</template>

<style scoped>
.dialog-title {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}
.dialog-body {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  padding-top: 8px;
  border-top: 1px solid var(--color-border-2);
  margin-top: 8px;
}
</style>

// src/components/containers/ContainerDialog.svelte
<script>
  import { t } from "../../lib/i18n.svelte.js";

  // config: {
  //   title, icon, width,
  //   fields: [{ id, type, placeholder, value, onInput, enterSubmit }],
  //   loading, submitLabel, loadingLabel, canSubmit,
  //   onSubmit, onClose,
  // }
  let { config } = $props();
</script>

<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
  <div class="w-full {config.width} bg-nx-surface border border-nx-border rounded-lg shadow-xl overflow-hidden">
    <div class="flex items-center justify-between px-3 py-2 border-b border-nx-border">
      <h2 class="text-sm font-semibold text-nx-text flex items-center gap-1.5">
        {#if config.icon}<span class="material-symbols-outlined text-lg">{config.icon}</span>{/if}
        {config.title}
      </h2>
      <button class="text-nx-text-muted hover:text-nx-text" onclick={config.onClose}>
        <span class="material-symbols-outlined text-lg">close</span>
      </button>
    </div>
    <div class="p-3 {config.fields.length > 1 ? 'space-y-2' : ''}">
      {#each config.fields as f}
        <input
          id={f.id}
          type={f.type || "text"}
          value={f.value}
          oninput={(e) => f.onInput(e.currentTarget.value)}
          placeholder={f.placeholder}
          class="nx-input w-full h-8 text-xs"
          onkeydown={(e) => { if (e.key === 'Enter' && f.enterSubmit !== false) config.onSubmit(); }}
        />
      {/each}
      <div class="mt-3 flex justify-end gap-2">
        <button class="nx-btn h-7 text-xs" onclick={config.onClose}>{t("common.cancel")}</button>
        <button class="nx-btn nx-btn-primary h-7 text-xs" onclick={config.onSubmit} disabled={config.loading || !config.canSubmit}>
          {config.loading ? config.loadingLabel : config.submitLabel}
        </button>
      </div>
    </div>
  </div>
</div>
