// src/components/containers/ImagesTab.svelte
<script>
  import { t } from "../../lib/i18n.svelte.js";
  import ContainerIcons from "../../icons/ContainerIcons.svelte";

  let {
    items = [],
    loading = false,
    error = null,
    search = "",
    actionLoading = "",
    onPull,
    onBuild,
    onRefresh,
    onPush,
    onTag,
    onRemove,
  } = $props();

  function shortId(id) { return id ? id.substring(0, 12) : ""; }
  function formatCreated(created) { return created || "-"; }
  function formatSize(size) { return size || "-"; }
</script>

<div>
  <div class="mb-4 flex items-center justify-between">
    <div class="flex items-center gap-2">
      <button class="nx-btn text-xs h-7" onclick={onPull}>
        <span class="material-symbols-outlined text-sm">download</span>{t("docker.pull")}
      </button>
      <button class="nx-btn text-xs h-7" onclick={onBuild}>
        <span class="material-symbols-outlined text-sm">construction</span>{t("docker.build")}
      </button>
    </div>
    <button class="nx-btn nx-btn-ghost px-2 text-xs h-7" onclick={onRefresh} disabled={loading}>
      <span class="material-symbols-outlined text-sm {loading ? 'animate-spin' : ''}">refresh</span>
      {t("common.refresh")}
    </button>
  </div>

  <div class="nx-section">
    {#if loading && items.length === 0}
      <div class="flex items-center justify-center py-12">
        <span class="material-symbols-outlined animate-spin text-nx-text-muted text-3xl">progress_activity</span>
      </div>
    {:else if error}
      <div class="p-6 text-center">
        <span class="material-symbols-outlined text-nx-danger text-3xl">error</span>
        <div class="mt-2 text-sm text-nx-danger">{error}</div>
        <button class="nx-btn nx-btn-primary mt-4" onclick={onRefresh}>{t("common.retry")}</button>
      </div>
    {:else if items.length === 0}
      <div class="p-12 text-center">
        <ContainerIcons name="image" size={36} class="mx-auto text-nx-text-muted" />
        <div class="mt-3 text-sm text-nx-text-muted">{search ? t("docker.no_matching") : t("docker.no_images")}</div>
      </div>
    {:else}
      <table class="nx-table">
        <thead>
          <tr>
            <th>{t("docker.repository")}</th>
            <th>{t("docker.tag")}</th>
            <th>{t("docker.image_id")}</th>
            <th>{t("docker.created")}</th>
            <th class="text-right">{t("docker.size")}</th>
            <th class="text-right w-24">{t("docker.actions")}</th>
          </tr>
        </thead>
        <tbody>
          {#each items as img (img.id)}
            <tr>
              <td class="text-sm font-medium text-nx-text">{img.repository}</td>
              <td><span class="nx-pill font-mono text-[10px]">{img.tag}</span></td>
              <td class="font-mono text-xs text-nx-text-muted">{shortId(img.id)}</td>
              <td class="text-xs text-nx-text-muted">{formatCreated(img.created)}</td>
              <td class="text-right text-xs text-nx-text-secondary">{formatSize(img.size)}</td>
              <td class="text-right">
                <span class="flex items-center justify-end gap-1">
                  <button class="nx-btn text-xs h-7 px-2" onclick={() => onPush(img)}>{t("docker.push")}</button>
                  <button class="nx-btn text-xs h-7 px-2" onclick={() => onTag(img)}>{t("docker.tag")}</button>
                  <button class="nx-btn text-xs h-7 px-2 text-nx-danger"
                    onclick={() => onRemove(img.id, `${img.repository}:${img.tag}`)} disabled={actionLoading === img.id}>
                    {t("docker.delete")}
                  </button>
                </span>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
      <div class="flex items-center justify-between border-t border-nx-border px-4 py-2">
        <span class="text-xs text-nx-text-muted">{items.length} {t("docker.images_count")}</span>
      </div>
    {/if}
  </div>
</div>

// src/components/containers/ImagesTab.vue
<script setup>
import { computed } from "vue";
import { t } from "../../lib/i18n.js";
import ContainerIcons from "../../icons/ContainerIcons.vue";

const props = defineProps({
  items: { type: Array, default: () => [] },
  loading: { type: Boolean, default: false },
  error: { type: String, default: null },
  search: { type: String, default: "" },
  actionLoading: { type: String, default: "" },
});

const emit = defineEmits(["pull", "build", "refresh", "push", "tag", "remove"]);

function shortId(id) {
  return id ? id.substring(0, 12) : "";
}

const columns = computed(() => [
  { title: t("docker.repository"), slotName: "repo" },
  { title: t("docker.tag"), slotName: "tag", width: 110 },
  { title: t("docker.image_id"), slotName: "id", width: 120 },
  { title: t("docker.created"), slotName: "created", width: 130 },
  { title: t("docker.size"), slotName: "size", align: "right", width: 100 },
  { title: t("docker.actions"), slotName: "actions", align: "right", width: 190 },
]);
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center gap-2">
        <a-button size="small" @click="emit('pull')">
          <template #icon><icon-download /></template>
          {{ t("docker.pull") }}
        </a-button>
        <a-button size="small" @click="emit('build')">
          <template #icon><icon-build /></template>
          {{ t("docker.build") }}
        </a-button>
      </div>
      <a-button size="small" @click="emit('refresh')" :disabled="loading">
        <template #icon>
          <icon-refresh :spin="loading" />
        </template>
        {{ t("common.refresh") }}
      </a-button>
    </div>

    <a-card :bordered="true" class="section-card">
      <a-spin :loading="loading && items.length === 0" class="w-full">
        <a-alert v-if="error" type="error" :message="error">
          <template #action>
            <a-button size="mini" @click="emit('refresh')">{{ t("common.retry") }}</a-button>
          </template>
        </a-alert>

        <a-empty
          v-else-if="items.length === 0"
          :description="search ? t('docker.no_matching') : t('docker.no_images')"
        >
          <template #image>
            <ContainerIcons name="image" :size="36" class="empty-icon" />
          </template>
        </a-empty>

        <a-table
          v-else
          :data="items"
          :columns="columns"
          :pagination="false"
          :bordered="{ wrapper: false, cell: false }"
          :loading="loading"
          size="small"
          :row-key="(r) => r.id"
        >
          <template #repo="{ record }">
            <span class="cell-name">{{ record.repository }}</span>
          </template>
          <template #tag="{ record }">
            <a-tag size="small" class="mono-tag">{{ record.tag }}</a-tag>
          </template>
          <template #id="{ record }">
            <span class="cell-mono cell-muted">{{ shortId(record.id) }}</span>
          </template>
          <template #created="{ record }">
            <span class="cell-muted">{{ record.created || "-" }}</span>
          </template>
          <template #size="{ record }">
            <span class="cell-muted">{{ record.size || "-" }}</span>
          </template>
          <template #actions="{ record }">
            <div class="actions-row">
              <a-button size="mini" @click="emit('push', record)">{{ t("docker.push") }}</a-button>
              <a-button size="mini" @click="emit('tag', record)">{{ t("docker.tag") }}</a-button>
              <a-button
                size="mini"
                status="danger"
                :disabled="actionLoading === record.id"
                @click="emit('remove', record.id, `${record.repository}:${record.tag}`)"
              >{{ t("docker.delete") }}</a-button>
            </div>
          </template>
        </a-table>
        <div v-if="items.length" class="table-footer">
          <span>{{ items.length }} {{ t("docker.images_count") }}</span>
        </div>
      </a-spin>
    </a-card>
  </div>
</template>

<style scoped>
.section-card {
  border-radius: 10px;
}
.cell-name {
  font-weight: 500;
  color: var(--color-text-1);
}
.cell-mono {
  font-family: "JetBrains Mono", monospace;
  font-size: 12px;
}
.cell-muted {
  color: var(--color-text-3);
}
.mono-tag {
  font-family: "JetBrains Mono", monospace;
}
.actions-row {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 6px;
}
.table-footer {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  padding: 8px 4px 0;
  font-size: 12px;
  color: var(--color-text-3);
  border-top: 1px solid var(--color-border-2);
  margin-top: 8px;
}
.empty-icon {
  color: var(--color-text-3);
}
</style>
