// src/components/containers/NetworksTab.vue
<script setup>
import { computed } from "vue";
import { t } from "../../lib/i18n.js";
import ContainerIcons from "../../icons/ContainerIcons.vue";

const props = defineProps({
  items: { type: Array, default: () => [] },
  loading: { type: Boolean, default: false },
  error: { type: String, default: null },
  actionLoading: { type: String, default: "" },
});

const emit = defineEmits(["create", "refresh", "remove"]);

const columns = computed(() => [
  { title: t("docker.name"), slotName: "name" },
  { title: t("docker.driver"), slotName: "driver", width: 160 },
  { title: t("docker.scope"), slotName: "scope", width: 140 },
  { title: t("docker.actions"), slotName: "actions", align: "right", width: 90 },
]);
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-4">
      <a-button size="small" @click="emit('create')">
        <template #icon><icon-plus /></template>
        {{ t("docker.create") }}
      </a-button>
      <a-button size="small" @click="emit('refresh')" :disabled="loading">
        <template #icon>
          <icon-refresh :spin="loading" />
        </template>
        {{ t("common.refresh") }}
      </a-button>
    </div>

    <a-card :bordered="true" class="section-card">
      <a-spin :loading="loading && items.length === 0" class="w-full">
        <a-alert v-if="error" type="error" :message="error">
          <template #action>
            <a-button size="mini" @click="emit('refresh')">{{ t("common.retry") }}</a-button>
          </template>
        </a-alert>

        <a-empty v-else-if="items.length === 0" :description="t('docker.no_networks')">
          <template #image>
            <ContainerIcons name="network" :size="36" class="empty-icon" />
          </template>
        </a-empty>

        <a-table
          v-else
          :data="items"
          :columns="columns"
          :pagination="false"
          :bordered="{ wrapper: false, cell: false }"
          :loading="loading"
          size="small"
          :row-key="(r) => r.name"
        >
          <template #name="{ record }">
            <span class="cell-name">{{ record.name }}</span>
          </template>
          <template #driver="{ record }">
            <span class="cell-muted">{{ record.driver }}</span>
          </template>
          <template #scope="{ record }">
            <span class="cell-muted">{{ record.scope }}</span>
          </template>
          <template #actions="{ record }">
            <a-button
              size="mini"
              status="danger"
              :disabled="actionLoading === record.name"
              @click="emit('remove', record.name)"
            >{{ t("docker.delete") }}</a-button>
          </template>
        </a-table>
      </a-spin>
    </a-card>
  </div>
</template>

<style scoped>
.section-card {
  border-radius: 10px;
}
.cell-name {
  font-weight: 500;
  color: var(--color-text-1);
}
.cell-muted {
  color: var(--color-text-3);
}
.empty-icon {
  color: var(--color-text-3);
}
</style>

// src/components/containers/NetworksTab.svelte
<script>
  import { t } from "../../lib/i18n.svelte.js";
  import ContainerIcons from "../../icons/ContainerIcons.svelte";

  let {
    items = [],
    loading = false,
    error = null,
    actionLoading = "",
    onCreate,
    onRefresh,
    onRemove,
  } = $props();
</script>

<div>
  <div class="mb-4 flex items-center justify-between">
    <div class="flex items-center gap-2">
      <button class="nx-btn text-xs h-7" onclick={onCreate}>
        <span class="material-symbols-outlined text-sm">add</span>{t("docker.create")}
      </button>
    </div>
    <button class="nx-btn nx-btn-ghost px-2 text-xs h-7" onclick={onRefresh} disabled={loading}>
      <span class="material-symbols-outlined text-sm {loading ? 'animate-spin' : ''}">refresh</span>
      {t("common.refresh")}
    </button>
  </div>

  <div class="nx-section">
    {#if loading && items.length === 0}
      <div class="flex items-center justify-center py-12">
        <span class="material-symbols-outlined animate-spin text-nx-text-muted text-3xl">progress_activity</span>
      </div>
    {:else if error}
      <div class="p-6 text-center">
        <span class="material-symbols-outlined text-nx-danger text-3xl">error</span>
        <div class="mt-2 text-sm text-nx-danger">{error}</div>
        <button class="nx-btn nx-btn-primary mt-4" onclick={onRefresh}>{t("common.retry")}</button>
      </div>
    {:else if items.length === 0}
      <div class="p-12 text-center">
        <ContainerIcons name="network" size={36} class="mx-auto text-nx-text-muted" />
        <div class="mt-3 text-sm text-nx-text-muted">{t("docker.no_networks")}</div>
      </div>
    {:else}
      <table class="nx-table">
        <thead>
          <tr>
            <th>{t("docker.name")}</th>
            <th>{t("docker.driver")}</th>
            <th>{t("docker.scope")}</th>
            <th class="text-right w-24">{t("docker.actions")}</th>
          </tr>
        </thead>
        <tbody>
          {#each items as n (n.name)}
            <tr>
              <td class="text-sm font-medium text-nx-text">{n.name}</td>
              <td class="text-xs text-nx-text-secondary">{n.driver}</td>
              <td class="text-xs text-nx-text-muted">{n.scope}</td>
              <td class="text-right">
                <button class="nx-btn text-xs h-7 px-2 text-nx-danger"
                  onclick={() => onRemove(n.name)} disabled={actionLoading === n.name}>
                  {t("docker.delete")}
                </button>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </div>
</div>
