// src/routes/AppUninstaller.svelte
<script>
  import { invoke } from "@tauri-apps/api/core";
  import TableSkeleton from "../components/skeleton/TableSkeleton.svelte";
  import { onMount } from "svelte";
  import { showToast } from "../lib/toast.svelte.js";
  import { showConfirm } from "../lib/confirm.svelte.js";
  import { t, tFormat } from "../lib/i18n.svelte.js";
  import { friendlyError } from "../lib/errors.svelte.js";

  let apps = $state([]);
  let loading = $state(true);
  let error = $state(null);
  let search = $state("");

  // Uninstall state
  let uninstalling = $state(null);  // app name being uninstalled

  // Residue scan state
  let scanning = $state(null);       // app name being scanned
  let residueScans = $state({});     // { [appName]: ResidueScan }
  let selectedResidues = $state({}); // { [appName]: { [path]: bool } }
  let cleaningResidues = $state(null); // app name being cleaned
  let scanErrors = $state({});       // { [appName]: string }

  async function loadApps() {
    try {
      loading = true;
      error = null;
      apps = await invoke("list_installed_apps");
    } catch (err) {
      error = friendlyError(err);
    } finally {
      loading = false;
    }
  }

  async function handleUninstall(app) {
    if (!await showConfirm(tFormat('uninstall_mgr.confirm', { name: app.name }) || `Uninstall ${app.name}?`)) return;

    uninstalling = app.name;
    try {
      const result = await invoke("uninstall_software_deep", { packageName: app.name, appName: app.name });
      showToast(result);
      // Auto-scan after uninstall
      await scanResidues(app, true);
      await loadApps();
    } catch (err) {
      showToast(tFormat("uninstall_mgr.failed", { error: friendlyError(err) }));
      // Even if uninstall failed, offer to scan & clean residues
      await scanResidues(app, true);
    } finally {
      uninstalling = null;
    }
  }

  async function handleForceUninstall(app) {
    if (!await showConfirm(tFormat('uninstall_mgr.force_confirm', { name: app.name }) || `Force uninstall ${app.name}? This will kill all related processes and remove ALL residue files.`)) return;

    uninstalling = app.name;
    try {
      const result = await invoke("force_uninstall_software", { packageName: app.name, appName: app.name });
      showToast(result);
      const name = String(app.name);
      const newScans = {};
      for (const k of Object.keys(residueScans)) {
        if (k !== name) newScans[k] = residueScans[k];
      }
      residueScans = newScans;
      const newSel = {};
      for (const k of Object.keys(selectedResidues)) {
        if (k !== name) newSel[k] = selectedResidues[k];
      }
      selectedResidues = newSel;
      await loadApps();
    } catch (err) {
      showToast(tFormat("uninstall_mgr.force_failed", { error: friendlyError(err) }));
    } finally {
      uninstalling = null;
    }
  }

  async function scanResidues(app, auto = false) {
    scanning = app.name;
    scanErrors[app.name] = null;
    try {
      const scan = await invoke("scan_app_residues", { appName: app.name, packageName: app.name });
      residueScans[app.name] = scan;
      // Select all residue items by default
      const sel = {};
      for (const item of getAllItems(scan)) {
        if (item.is_safe_to_delete) {
          sel[item.path] = true;
        }
      }
      selectedResidues[app.name] = sel;
    } catch (err) {
      scanErrors[app.name] = friendlyError(err);
      if (!auto) showToast(tFormat("uninstall_mgr.scan_failed", { error: friendlyError(err) }));
    } finally {
      scanning = null;
    }
  }

  function getAllItems(scan) {
    if (!scan) return [];
    let items = [
      ...scan.directories,
      ...scan.files,
      ...scan.shortcuts,
      ...scan.services,
    ];
    // registry_keys only exists on Windows
    if (scan.registry_keys) {
      items = items.concat(scan.registry_keys);
    }
    return items;
  }

  function getCategoryIcon(cat) {
    switch (cat) {
      case "config": return "settings";
      case "cache": return "cached";
      case "log": return "description";
      case "temp": return "delete";
      case "data": return "folder";
      case "shortcut": return "shortcut";
      case "service": return "precision_manufacturing";
      case "registry": return "database";
      default: return "file_present";
    }
  }

  function getCategoryLabel(cat) {
    switch (cat) {
      case "config": return t("residue.type_config");
      case "cache": return t("residue.type_cache");
      case "log": return t("residue.type_log");
      case "temp": return t("residue.type_temp");
      case "data": return t("residue.type_data");
      case "shortcut": return t("residue.type_shortcut");
      case "service": return t("residue.type_service");
      case "registry": return t("residue.type_registry");
      default: return cat;
    }
  }

  function formatSize(bytes) {
    if (bytes === 0) return "0 B";
    const units = ["B", "KB", "MB", "GB"];
    let i = 0;
    let size = bytes;
    while (size >= 1024 && i < units.length - 1) {
      size /= 1024;
      i++;
    }
    return `${size.toFixed(1)} ${units[i]}`;
  }

  async function cleanSelected(appName) {
    const appScan = residueScans[appName];
    if (!appScan) return;

    const sel = selectedResidues[appName] || {};
    const paths = Object.keys(sel).filter(p => sel[p]);
    if (paths.length === 0) {
      showToast(t("uninstall_mgr.nothing_selected"));
      return;
    }

    if (!await showConfirm(tFormat('uninstall_mgr.confirm_clean', { count: paths.length }) || `Clean ${paths.length} selected residue item(s)?`)) return;

    cleaningResidues = appName;
    try {
      const result = await invoke("clean_specific_residues", { items: paths });
      showToast(result);
      // Re-scan after cleaning
      await scanResidues({ name: appName });
    } catch (err) {
      showToast(tFormat("uninstall_mgr.clean_failed", { error: friendlyError(err) }));
    } finally {
      cleaningResidues = null;
    }
  }

  function toggleScan(app) {
    if (residueScans[app.name]) {
      // Close scan panel
      const name = String(app.name);
      const newScans = {};
      for (const k of Object.keys(residueScans)) {
        if (k !== name) newScans[k] = residueScans[k];
      }
      residueScans = newScans;
      const newSel = {};
      for (const k of Object.keys(selectedResidues)) {
        if (k !== name) newSel[k] = selectedResidues[k];
      }
      selectedResidues = newSel;
    } else {
      scanResidues(app);
    }
  }

  let filtered = $derived(
    search.trim()
      ? apps.filter(a =>
          a.name.toLowerCase().includes(search.toLowerCase()) ||
          a.source.toLowerCase().includes(search.toLowerCase()) ||
          a.version.toLowerCase().includes(search.toLowerCase())
        )
      : apps
  );

  let sourceFilter = $state("all");
  let sources = $derived([...new Set(apps.map(a => a.source))].sort());

  onMount(() => {
    loadApps();
  });
</script>

<div class="mx-auto max-w-5xl p-5">
  <!-- Header -->
  <div class="mb-6 flex items-center justify-between">
    <div>
      <h1 class="text-xl font-semibold text-nx-text">{t("uninstall_mgr.title")}</h1>
      <p class="mt-1 text-xs text-nx-text-muted">{t("uninstall_mgr.desc")}</p>
    </div>
    <button
      class="nx-btn nx-btn-ghost flex items-center gap-2 cursor-pointer"
      onclick={loadApps}
    >
      <span class="material-symbols-outlined text-lg">refresh</span>
      {t("common.refresh")}
    </button>
  </div>

  <!-- Search & Filter -->
  <div class="mb-4 flex items-center gap-3">
    <div class="nx-search flex-1">
      <span class="nx-search-icon material-symbols-outlined">search</span>
      <input
        class="nx-input"
        type="text"
        placeholder={t("uninstall_mgr.search")}
        value={search}
        oninput={(e) => { search = e.currentTarget.value; }}
      />
      {#if search}
        <button
          class="nx-search-clear material-symbols-outlined cursor-pointer"
          onclick={() => { search = ""; }}
        >
          close
        </button>
      {/if}
    </div>
    <select
      class="nx-input px-3 py-2 text-sm"
      value={sourceFilter}
      onchange={(e) => sourceFilter = e.currentTarget.value}
    >
      <option value="all">{t("uninstall_mgr.all_sources")}</option>
      {#each sources as src}
        <option value={src}>{src}</option>
      {/each}
    </select>
  </div>

  <!-- App List -->
  <div class="nx-section">
    {#if loading}
      <TableSkeleton />
    {:else if error}
      <div class="nx-empty">
        <span class="material-symbols-outlined text-nx-danger text-3xl">error</span>
        <div class="mt-2 text-sm text-nx-danger">{error}</div>
        <button class="nx-btn nx-btn-primary mt-4 cursor-pointer" onclick={loadApps}>{t("common.retry")}</button>
      </div>
    {:else if apps.length === 0}
      <div class="nx-empty p-12">
        <span class="material-symbols-outlined text-nx-text-muted text-4xl">delete</span>
        <div class="mt-4 text-sm text-nx-text-muted">{t("uninstall_mgr.no_apps")}</div>
      </div>
    {:else}
      <!-- Column headers -->
      <div class="hidden md:flex items-center border-b border-nx-border px-4 py-2 text-xs text-nx-text-muted font-medium">
        <div class="min-w-0" style="width: 40%;">{t("uninstall_mgr.app_name")}</div>
        <div class="text-right" style="width: 18%;">{t("uninstall_mgr.version")}</div>
        <div class="text-right" style="width: 16%;">{t("uninstall_mgr.source")}</div>
        <div class="text-right" style="width: 26%;">{t("common.actions")}</div>
      </div>

      {#each filtered as app (app.name + app.source)}
        {#if sourceFilter === "all" || app.source === sourceFilter}
          <div class="border-b border-nx-border last:border-0">
            <!-- Main row -->
            <div class="flex items-center px-4 py-3 hover:bg-nx-surface-hover transition-colors">
              <!-- Name -->
              <div class="min-w-0" style="width: 40%;">
                <span class="text-sm font-medium text-nx-text">{app.name}</span>
                {#if residueScans[app.name]}
                  <span class="ml-2 inline-block rounded bg-nx-warning/10 px-1.5 py-0.5 text-[10px] font-medium text-nx-warning">
                    {tFormat("uninstall_mgr.residues_found", { count: residueScans[app.name].total_items })}
                  </span>
                {/if}
              </div>

              <!-- Version -->
              <div class="text-right" style="width: 18%;">
                <span class="text-xs font-mono text-nx-text-secondary">{app.version}</span>
              </div>

              <!-- Source (Package Manager) -->
              <div class="text-right" style="width: 16%;">
                <span class="inline-block rounded bg-nx-accent/10 px-2 py-0.5 text-xs font-medium text-nx-accent">{app.source}</span>
              </div>

              <!-- Actions -->
              <div class="flex justify-end gap-1" style="width: 26%;">
                <button
                  class="nx-btn nx-btn-ghost px-2 py-1 text-xs cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed"
                  onclick={() => toggleScan(app)}
                  disabled={scanning === app.name || cleaningResidues === app.name}
                >
                  {#if scanning === app.name}
                    <span class="material-symbols-outlined text-xs inline nx-animate-spin">progress_activity</span>
                  {:else}
                    <span class="material-symbols-outlined text-xs inline">search</span>
                  {/if}
                  {residueScans[app.name] ? t("uninstall_mgr.close_scan") : t("uninstall_mgr.residue_scan")}
                </button>
                <button
                  class="nx-btn text-xs text-nx-danger hover:bg-nx-danger/10 px-3 py-1 cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed"
                  onclick={() => handleUninstall(app)}
                  disabled={uninstalling !== null || scanning === app.name}
                >
                  {#if uninstalling === app.name}
                    <span class="material-symbols-outlined text-xs inline nx-animate-spin">progress_activity</span>
                  {:else}
                    {t("uninstall_mgr.uninstall")}
                  {/if}
                </button>
              </div>
            </div>

            <!-- Residue scan panel (expandable) -->
            {#if residueScans[app.name]}
              {@const scan = residueScans[app.name]}
              <div class="border-t border-nx-border bg-nx-surface/50 px-4 py-3">
                {#if scanErrors[app.name]}
                  <div class="text-sm text-nx-danger">{scanErrors[app.name]}</div>
                {:else}
                  <!-- Summary bar -->
                  <div class="mb-3 flex items-center justify-between">
                    <div class="flex items-center gap-3 text-xs text-nx-text-muted">
                      <span>
                    <span class="font-medium text-nx-text">{scan.total_items}</span> {t("uninstall_mgr.residues_count")}
                      </span>
                      <span>
                        {t("uninstall_mgr.total_size")} <span class="font-medium text-nx-text">{formatSize(scan.total_size)}</span>
                      </span>
                    </div>
                    <div class="flex gap-2">
                      <button
                        class="nx-btn nx-btn-ghost flex items-center gap-1 px-2.5 py-1 text-xs cursor-pointer disabled:opacity-30"
                        onclick={() => cleanSelected(app.name)}
                        disabled={cleaningResidues !== null || scanning !== null}
                      >
                        {#if cleaningResidues === app.name}
                          <span class="material-symbols-outlined text-xs nx-animate-spin">progress_activity</span>
                        {:else}
                          <span class="material-symbols-outlined text-xs">cleaning_services</span>
                        {/if}
                        {t("uninstall_mgr.clean_selected")}
                      </button>
                      <button
                        class="nx-btn nx-btn-danger flex items-center gap-1 px-2.5 py-1 text-xs cursor-pointer disabled:opacity-30"
                        onclick={() => handleForceUninstall(app)}
                        disabled={uninstalling !== null || cleaningResidues !== null}
                      >
                        <span class="material-symbols-outlined text-xs">delete_forever</span>
                        {t("uninstall_mgr.force_uninstall")}
                      </button>
                    </div>
                  </div>

                  <!-- Residue items grouped by category -->
                  {#if getAllItems(scan).length === 0}
                    <div class="py-4 text-center text-sm text-nx-text-muted">
                      <span class="material-symbols-outlined text-lg inline">check_circle</span>
                      {t("uninstall_mgr.no_residues")}
                    </div>
                  {:else}
                    {#each ["directories", "files", "shortcuts", "services", ...(scan.registry_keys ? ["registry_keys"] : [])] as key}
                      {#if scan[key] && scan[key].length > 0}
                        <div class="mb-2">
                          <div class="mb-1 flex items-center gap-2">
                            <button
                              class="flex items-center gap-1 text-xs font-medium text-nx-text cursor-pointer hover:text-nx-accent"
                              onclick={() => {
                                const sel = { ...(selectedResidues[app.name] || {}) };
                                const allSelected = scan[key].every(item => sel[item.path]);
                                for (const item of scan[key]) {
                                  if (item.is_safe_to_delete) {
                                    sel[item.path] = !allSelected;
                                  }
                                }
                                selectedResidues[app.name] = sel;
                              }}
                            >
                              <span class="material-symbols-outlined text-sm">
                                {key === "directories" ? "folder" : key === "files" ? "description" : key === "shortcuts" ? "shortcut" : key === "services" ? "precision_manufacturing" : "database"}
                              </span>
                              {t("residue.category_" + (key === "registry_keys" ? "registry" : key))}
                              <span class="text-nx-text-muted">({scan[key].length})</span>
                            </button>
                          </div>
                          <div class="space-y-0.5">
                            {#each scan[key] as item}
                              <div class="flex items-center gap-2 rounded px-2 py-1 text-xs hover:bg-nx-surface-hover">
                                <input
                                  type="checkbox"
                                  checked={selectedResidues[app.name]?.[item.path] ?? true}
                                  disabled={!item.is_safe_to_delete}
                                  onchange={(e) => {
                                    const sel = { ...(selectedResidues[app.name] || {}) };
                                    if (e.currentTarget.checked) {
                                      sel[item.path] = true;
                                    } else {
                                      delete sel[item.path];
                                    }
                                    selectedResidues[app.name] = sel;
                                  }}
                                  class="accent-nx-accent cursor-pointer shrink-0"
                                />
                                <span class="material-symbols-outlined text-nx-text-muted text-sm shrink-0">
                                  {getCategoryIcon(item.category)}
                                </span>
                                <span class="flex-1 truncate text-nx-text-secondary" title={item.path}>
                                  {item.path}
                                </span>
                                <span class="shrink-0 font-mono text-nx-text-muted">
                                  {item.size > 0 ? formatSize(item.size) : ""}
                                </span>
                                  {#if !item.is_safe_to_delete}
                                  <span class="shrink-0 rounded bg-nx-warning/10 px-1 py-0.5 text-[10px] text-nx-warning">{t("uninstall_mgr.caution")}</span>
                                {/if}
                              </div>
                            {/each}
                          </div>
                        </div>
                      {/if}
                    {/each}
                  {/if}
                {/if}
              </div>
            {/if}
          </div>
        {/if}
      {/each}

      <!-- Footer count -->
      <div class="flex items-center justify-between border-t border-nx-border px-4 py-2">
        <span class="text-xs text-nx-text-muted">
          {filtered.length} / {apps.length} {t("uninstall_mgr.apps_count")}
        </span>
      </div>
    {/if}
  </div>
</div>

// src/views/AppUninstaller.vue
<script setup>
import { ref, computed, onMounted } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { showToast } from "../lib/toast.js";
import { showConfirm } from "../lib/confirm.js";
import { t, tFormat } from "../lib/i18n.js";
import { friendlyError } from "../lib/errors.js";
import AppIcon from "../components/AppIcon.vue";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Spinner } from "@/components/ui/spinner";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Alert,
  AlertDescription,
} from "@/components/ui/alert";
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyMedia,
} from "@/components/ui/empty";

const apps = ref([]);
const loading = ref(true);
const error = ref(null);
const search = ref("");
const sourceFilter = ref("all");
const uninstalling = ref(null);
const scanning = ref(null);
const residueScans = ref({});
const selectedResidues = ref({});
const cleaningResidues = ref(null);
const scanErrors = ref({});

async function loadApps() {
  try {
    loading.value = true;
    error.value = null;
    apps.value = await invoke("list_installed_apps");
  } catch (err) {
    error.value = friendlyError(err);
  } finally {
    loading.value = false;
  }
}

async function handleUninstall(app) {
  if (
    !(await showConfirm(
      tFormat("uninstall_mgr.confirm", { name: app.name }) || `Uninstall ${app.name}?`
    ))
  )
    return;

  uninstalling.value = app.name;
  try {
    const result = await invoke("uninstall_software_deep", {
      packageName: app.name,
      appName: app.name,
    });
    showToast(result);
    await scanResidues(app, true);
    await loadApps();
  } catch (err) {
    showToast(tFormat("uninstall_mgr.failed", { error: friendlyError(err) }));
    await scanResidues(app, true);
  } finally {
    uninstalling.value = null;
  }
}

async function handleForceUninstall(app) {
  if (
    !(await showConfirm(
      tFormat("uninstall_mgr.force_confirm", { name: app.name }) ||
        `Force uninstall ${app.name}? This will kill all related processes and remove ALL residue files.`
    ))
  )
    return;

  uninstalling.value = app.name;
  try {
    const result = await invoke("force_uninstall_software", {
      packageName: app.name,
      appName: app.name,
    });
    showToast(result);
    const name = String(app.name);
    delete residueScans.value[name];
    delete selectedResidues.value[name];
    await loadApps();
  } catch (err) {
    showToast(tFormat("uninstall_mgr.force_failed", { error: friendlyError(err) }));
  } finally {
    uninstalling.value = null;
  }
}

async function scanResidues(app, auto = false) {
  scanning.value = app.name;
  scanErrors.value[app.name] = null;
  try {
    const scan = await invoke("scan_app_residues", {
      appName: app.name,
      packageName: app.name,
    });
    residueScans.value[app.name] = scan;
    // 默认不自动勾选任何残留项。用户需手动勾选后再清理
    selectedResidues.value[app.name] = {};
  } catch (err) {
    scanErrors.value[app.name] = friendlyError(err);
    if (!auto) {
      showToast(tFormat("uninstall_mgr.scan_failed", { error: friendlyError(err) }));
    }
  } finally {
    scanning.value = null;
  }
}

function getAllItems(scan) {
  if (!scan) return [];
  let items = [
    ...(scan.directories || []),
    ...(scan.files || []),
    ...(scan.shortcuts || []),
    ...(scan.services || []),
  ];
  if (scan.registry_keys) {
    items = items.concat(scan.registry_keys);
  }
  return items;
}

function getCategoryIcon(cat) {
  const map = {
    config: "icon-settings",
    cache: "icon-history",
    log: "icon-file",
    temp: "icon-delete",
    data: "icon-folder",
    shortcut: "icon-shortcut",
    service: "icon-tool",
    registry: "icon-database",
  };
  return map[cat] || "icon-file";
}

function getCategoryLabel(cat) {
  const map = {
    config: t("residue.type_config"),
    cache: t("residue.type_cache"),
    log: t("residue.type_log"),
    temp: t("residue.type_temp"),
    data: t("residue.type_data"),
    shortcut: t("residue.type_shortcut"),
    service: t("residue.type_service"),
    registry: t("residue.type_registry"),
  };
  return map[cat] || cat;
}

function formatSize(bytes) {
  if (bytes === 0) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  let i = 0;
  let size = bytes;
  while (size >= 1024 && i < units.length - 1) {
    size /= 1024;
    i++;
  }
  return `${size.toFixed(1)} ${units[i]}`;
}

async function cleanSelected(appName) {
  const appScan = residueScans.value[appName];
  if (!appScan) return;

  const sel = selectedResidues.value[appName] || {};
  const paths = Object.keys(sel).filter((p) => sel[p]);
  if (paths.length === 0) {
    showToast(t("uninstall_mgr.nothing_selected"));
    return;
  }

  if (
    !(await showConfirm(
      tFormat("uninstall_mgr.confirm_clean", { count: paths.length }) ||
        `Clean ${paths.length} selected residue item(s)?`
    ))
  )
    return;

  cleaningResidues.value = appName;
  try {
    const result = await invoke("clean_specific_residues", { items: paths });
    showToast(result);
    await scanResidues({ name: appName });
  } catch (err) {
    showToast(tFormat("uninstall_mgr.clean_failed", { error: friendlyError(err) }));
  } finally {
    cleaningResidues.value = null;
  }
}

function toggleScan(app) {
  if (residueScans.value[app.name]) {
    delete residueScans.value[app.name];
    delete selectedResidues.value[app.name];
  } else {
    scanResidues(app);
  }
}

const filtered = computed(() => {
  const q = search.value.trim().toLowerCase();
  let list = apps.value;
  if (sourceFilter.value !== "all") {
    list = list.filter((a) => a.source === sourceFilter.value);
  }
  if (q) {
    list = list.filter(
      (a) =>
        a.name.toLowerCase().includes(q) ||
        a.source.toLowerCase().includes(q) ||
        a.version.toLowerCase().includes(q)
    );
  }
  return list;
});

const sources = computed(() => [...new Set(apps.value.map((a) => a.source))].sort());

const residueKeys = (scan) => [
  "directories",
  "files",
  "shortcuts",
  "services",
  ...(scan.registry_keys ? ["registry_keys"] : []),
];

function toggleAllInKey(appName, key, items) {
  const sel = { ...(selectedResidues.value[appName] || {}) };
  const allSelected = items.every((item) => sel[item.path]);
  for (const item of items) {
    if (item.is_safe_to_delete) {
      if (allSelected) delete sel[item.path];
      else sel[item.path] = true;
    }
  }
  selectedResidues.value[appName] = sel;
}

function toggleItem(appName, path, checked) {
  const sel = { ...(selectedResidues.value[appName] || {}) };
  if (checked) sel[path] = true;
  else delete sel[path];
  selectedResidues.value[appName] = sel;
}

const isSelected = (appName, path) => !!selectedResidues.value[appName]?.[path];

onMounted(() => {
  loadApps();
});
</script>

<template>
  <div class="page uninstall-page">
    <!-- Header -->
    <div class="page-header">
      <div>
        <h1 class="page-title">{{ t("uninstall_mgr.title") }}</h1>
        <p class="page-desc">{{ t("uninstall_mgr.desc") }}</p>
      </div>
      <Button variant="outline" @click="loadApps">
        <AppIcon name="refresh" class="size-4" />
        {{ t("common.refresh") }}
      </Button>
    </div>

    <!-- Search & Filter -->
    <div class="mb-4 flex items-center gap-3">
      <div class="relative flex-1">
        <AppIcon
          name="search"
          class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"
        />
        <Input
          v-model="search"
          :placeholder="t('uninstall_mgr.search')"
          class="pl-9"
        />
      </div>
      <Select v-model="sourceFilter">
        <SelectTrigger class="w-[180px]">
          <SelectValue :placeholder="t('uninstall_mgr.all_sources')" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="all">{{ t("uninstall_mgr.all_sources") }}</SelectItem>
          <SelectItem v-for="src in sources" :key="src" :value="src">{{ src }}</SelectItem>
        </SelectContent>
      </Select>
    </div>

    <!-- App List -->
    <Card class="shadow-sm">
      <!-- Loading -->
      <CardContent v-if="loading" class="space-y-3 py-4">
        <Skeleton class="h-10 w-full" />
        <Skeleton class="h-10 w-full" />
        <Skeleton class="h-10 w-full" />
      </CardContent>

      <!-- Error -->
      <CardContent v-else-if="error" class="py-4">
        <Alert variant="destructive">
          <AppIcon name="close-circle-fill" class="size-4" />
          <AlertDescription>{{ error }}</AlertDescription>
        </Alert>
        <Button variant="default" class="mt-3" @click="loadApps">
          {{ t("common.retry") }}
        </Button>
      </CardContent>

      <!-- Empty -->
      <CardContent v-else-if="apps.length === 0" class="py-4">
        <Empty class="py-5">
          <EmptyMedia>
            <AppIcon name="delete" class="size-10 text-muted-foreground/60" />
          </EmptyMedia>
          <EmptyContent>
            <EmptyDescription>
              {{ t("uninstall_mgr.no_apps") }}
            </EmptyDescription>
          </EmptyContent>
        </Empty>
      </CardContent>

      <template v-else>
        <!-- Column headers -->
        <div class="flex items-center border-b border-border px-4 py-2 text-xs font-medium text-muted-foreground">
          <div class="col-name">{{ t("uninstall_mgr.app_name") }}</div>
          <div class="col-version">{{ t("uninstall_mgr.version") }}</div>
          <div class="col-source">{{ t("uninstall_mgr.source") }}</div>
          <div class="col-actions">{{ t("common.actions") }}</div>
        </div>

        <!-- Rows -->
        <div
          v-for="app in filtered"
          :key="`${app.name}-${app.source}`"
          class="border-b border-border last:border-b-0"
        >
          <!-- Main row -->
          <div class="flex items-center px-4 py-3 transition-colors hover:bg-muted">
            <!-- Name -->
            <div class="col-name">
              <img
                v-if="app.icon"
                :src="app.icon"
                alt=""
                class="size-7 shrink-0 rounded-md object-contain"
                loading="lazy"
                @error="(e) => (e.target.style.display = 'none')"
              />
              <span v-else class="flex size-7 shrink-0 items-center justify-center rounded-md bg-muted text-muted-foreground">
                <AppIcon name="apps" class="size-4" />
              </span>
              <span class="min-w-0 truncate text-sm font-medium text-foreground">{{ app.name }}</span>
              <Badge
                v-if="residueScans[app.name]"
                variant="outline"
                class="shrink-0 text-warning"
              >
                {{ tFormat("uninstall_mgr.residues_found", { count: residueScans[app.name].total_items }) }}
              </Badge>
            </div>

            <!-- Version -->
            <div class="col-version">
              <code class="rounded bg-muted px-1.5 py-0.5 font-mono text-xs">
                {{ app.version }}
              </code>
            </div>

            <!-- Source -->
            <div class="col-source">
              <Badge variant="secondary">{{ app.source }}</Badge>
            </div>

            <!-- Actions -->
            <div class="col-actions">
              <Button
                variant="outline"
                size="sm"
                :disabled="cleaningResidues === app.name"
                @click="toggleScan(app)"
              >
                <Spinner v-if="scanning === app.name" class="size-3.5" />
                <AppIcon v-else name="search" class="size-3.5" />
                {{ residueScans[app.name] ? t("uninstall_mgr.close_scan") : t("uninstall_mgr.residue_scan") }}
              </Button>
              <Button
                variant="destructive"
                size="sm"
                :disabled="uninstalling !== null || scanning === app.name"
                @click="handleUninstall(app)"
              >
                <Spinner v-if="uninstalling === app.name" class="size-3.5" />
                {{ t("uninstall_mgr.uninstall") }}
              </Button>
            </div>
          </div>

          <!-- Residue scan panel (expandable) -->
          <div v-if="residueScans[app.name]" class="border-t border-border bg-muted px-4 py-3">
            <Alert v-if="scanErrors[app.name]" variant="destructive" class="mb-3">
              <AlertDescription>{{ scanErrors[app.name] }}</AlertDescription>
            </Alert>
            <template v-else>
              <!-- Summary bar -->
              <div class="mb-3 flex items-center justify-between">
                <div class="flex items-center gap-4 text-xs text-muted-foreground">
                  <span>
                    <span class="font-semibold text-foreground">{{ residueScans[app.name].total_items }}</span>
                    {{ t("uninstall_mgr.residues_count") }}
                  </span>
                  <span>
                    {{ t("uninstall_mgr.total_size") }}
                    <span class="font-semibold text-foreground">{{ formatSize(residueScans[app.name].total_size) }}</span>
                  </span>
                </div>
                <div class="flex gap-2">
                  <Button
                    variant="default"
                    size="sm"
                    :disabled="cleaningResidues !== null || scanning !== null"
                    @click="cleanSelected(app.name)"
                  >
                    <Spinner v-if="cleaningResidues === app.name" class="size-3.5" />
                    <AppIcon v-else name="clean" class="size-3.5" />
                    {{ t("uninstall_mgr.clean_selected") }}
                  </Button>
                  <Button
                    variant="destructive"
                    size="sm"
                    :disabled="uninstalling !== null || cleaningResidues !== null"
                    @click="handleForceUninstall(app)"
                  >
                    <Spinner v-if="uninstalling === app.name" class="size-3.5" />
                    <AppIcon v-else name="delete" class="size-3.5" />
                    {{ t("uninstall_mgr.force_uninstall") }}
                  </Button>
                </div>
              </div>

              <!-- No residues -->
              <Empty
                v-if="getAllItems(residueScans[app.name]).length === 0"
                class="py-4"
              >
                <EmptyMedia>
                  <AppIcon name="check-circle" class="size-8 text-success" />
                </EmptyMedia>
                <EmptyContent>
                  <EmptyDescription>
                    {{ t("uninstall_mgr.no_residues") }}
                  </EmptyDescription>
                </EmptyContent>
              </Empty>

              <!-- Residue items grouped by category -->
              <div
                v-for="key in residueKeys(residueScans[app.name])"
                v-else
                :key="key"
                class="mb-2"
              >
                <template v-if="residueScans[app.name][key] && residueScans[app.name][key].length > 0">
                  <button
                    type="button"
                    class="mb-1 flex cursor-pointer items-center gap-1.5 border-0 bg-transparent p-0 text-xs font-medium text-foreground hover:text-primary"
                    @click="toggleAllInKey(app.name, key, residueScans[app.name][key])"
                  >
                    <AppIcon v-if="key === 'directories'" name="folder" class="size-3.5" />
                    <AppIcon v-else-if="key === 'files'" name="file" class="size-3.5" />
                    <AppIcon v-else-if="key === 'shortcuts'" name="shortcut" class="size-3.5" />
                    <AppIcon v-else-if="key === 'services'" name="tool" class="size-3.5" />
                    <AppIcon v-else name="database" class="size-3.5" />
                    {{
                      t("residue.category_" + (key === "registry_keys" ? "registry" : key))
                    }}
                    <span class="font-normal text-muted-foreground">({{ residueScans[app.name][key].length }})</span>
                  </button>
                  <div
                    v-for="item in residueScans[app.name][key]"
                    :key="item.path"
                    class="flex items-center gap-2 rounded-md px-2 py-1 text-xs hover:bg-accent"
                  >
                    <Checkbox
                      :model-value="isSelected(app.name, item.path)"
                      :disabled="!item.is_safe_to_delete"
                      @update:model-value="(c) => toggleItem(app.name, item.path, c)"
                    />
                    <AppIcon v-if="item.category === 'config'" name="settings" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else-if="item.category === 'cache'" name="history" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else-if="item.category === 'log'" name="file" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else-if="item.category === 'temp'" name="delete" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else-if="item.category === 'data'" name="folder" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else-if="item.category === 'shortcut'" name="shortcut" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else-if="item.category === 'service'" name="tool" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else-if="item.category === 'registry'" name="database" class="size-4 shrink-0 text-muted-foreground" />
                    <AppIcon v-else name="file" class="size-4 shrink-0 text-muted-foreground" />
                    <span class="min-w-0 flex-1 truncate text-muted-foreground" :title="item.path">{{ item.path }}</span>
                    <span class="shrink-0 font-mono text-muted-foreground">{{ item.size > 0 ? formatSize(item.size) : "" }}</span>
                    <Badge v-if="!item.is_safe_to_delete" variant="outline" class="text-warning">
                      {{ t("uninstall_mgr.caution") }}
                    </Badge>
                  </div>
                </template>
              </div>
            </template>
          </div>
        </div>

        <!-- Footer count -->
        <div class="flex items-center justify-end border-t border-border px-4 py-2 text-xs text-muted-foreground">
          <span>
            {{ filtered.length }} / {{ apps.length }} {{ t("uninstall_mgr.apps_count") }}
          </span>
        </div>
      </template>
    </Card>
  </div>
</template>

<style scoped>
.col-name {
  width: 40%;
  min-width: 0;
  display: flex;
  align-items: center;
  gap: 10px;
}
.col-version {
  width: 18%;
  text-align: right;
}
.col-source {
  width: 16%;
  text-align: right;
}
.col-actions {
  width: 26%;
  display: flex;
  justify-content: flex-end;
  gap: 6px;
}
</style>
