// src/routes/Dashboard.svelte
<script>
  import { invoke } from "@tauri-apps/api/core";
  import { onMount } from "svelte";
  import { t } from "../lib/i18n.svelte.js";
  import { navigate } from "../lib/stores.svelte.js";
  import { friendlyError } from "../lib/errors.svelte.js";

  let systemInfo = $state(null);
  let resourceUsage = $state(null);
  let loading = $state(true);
  let error = $state(null);

  function formatUptime(seconds) {
    const days = Math.floor(seconds / 86400);
    const hours = Math.floor((seconds % 86400) / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    return `${days}d ${hours}h ${minutes}m`;
  }

  async function loadSystemInfo() {
    try {
      loading = true;
      error = null;
      systemInfo = await invoke("get_system_info");
      resourceUsage = await invoke("get_resource_usage");
    } catch (err) {
      error = friendlyError(err);
    } finally {
      loading = false;
    }
  }

  async function refreshResourceUsage() {
    try {
      resourceUsage = await invoke("get_resource_usage");
    } catch (_) {}
  }

  function progressColor(val) {
    if (val > 80) return "var(--nx-danger)";
    if (val > 60) return "var(--nx-warning)";
    return "var(--nx-success)";
  }

  onMount(() => {
    loadSystemInfo();
    loadEnvironments();
    const interval = setInterval(refreshResourceUsage, 5000);
    return () => clearInterval(interval);
  });

  let stats = $derived([
    { 
      id: "cpu",
      label: "CPU Cores", 
      tkey: "dashboard.cpu_cores",
      value: systemInfo ? systemInfo.cpu_cores.toString() : "--", 
      sub: systemInfo?.cpu_model ? systemInfo.cpu_model.split(" ").slice(0, 2).join(" ") : "", 
      icon: "memory", 
    },
    { 
      id: "memory",
      label: "Memory", 
      tkey: "dashboard.memory",
      value: resourceUsage ? `${resourceUsage.memory_percent.toFixed(0)}%` : "--", 
      sub: resourceUsage ? `${resourceUsage.memory_used_gb}GB / ${resourceUsage.memory_total_gb}GB` : "", 
      icon: "sd_card", 
    },
    { 
      id: "disk",
      label: "Disk", 
      tkey: "dashboard.disk",
      value: resourceUsage ? `${resourceUsage.disk_percent.toFixed(0)}%` : "--", 
      sub: resourceUsage ? `${resourceUsage.disk_used_gb}GB / ${resourceUsage.disk_total_gb}GB` : "", 
      icon: "hard_drive", 
    },
  ]);

  let environments = $state([]);

  async function loadEnvironments() {
    try {
      environments = await invoke("list_environments");
    } catch (_) {}
  }

  const recentEnvs = $derived(
    environments.slice(0, 5).map(env => ({
      name: env.name,
      version: env.version,
      status: env.status === "Active" ? "Running" : "Stopped",
      statusColor: env.status === "Active" ? "running" : "stopped",
    }))
  );
</script>

<div class="nx-page mx-auto max-w-5xl p-8">
  <!-- Header -->
  <div class="mb-8 flex items-center justify-between">
    <div>
      <h1 class="text-xl font-semibold text-nx-text">{t("dashboard.overview")}</h1>
      <p class="mt-0.5 text-xs text-nx-text-muted">System status at a glance</p>
    </div>
    <button class="nx-btn nx-btn-primary flex items-center gap-2" onclick={() => navigate("/environments")}>
      <span class="material-symbols-outlined text-base">add</span>
      {t("dashboard.new_environment")}
    </button>
  </div>

  <!-- Stats Cards -->
  <div class="mb-8 grid grid-cols-3 gap-4">
    {#each stats as stat}
      <div class="nx-card p-5">
        <div class="mb-2 flex items-center justify-between">
          <span class="text-xs font-medium text-nx-text-secondary uppercase tracking-wider">{t(stat.tkey)}</span>
          <span class="material-symbols-outlined text-base text-nx-text-muted">{stat.icon}</span>
        </div>
        <div class="text-2xl font-semibold text-nx-text tracking-tight">{stat.value}</div>
        <div class="mt-0.5 text-xs text-nx-text-muted">{stat.sub}</div>
        {#if stat.id === "cpu" && resourceUsage}
          <div class="nx-progress mt-3">
            <div class="nx-progress-bar" style="width: {resourceUsage.cpu_usage}%; background: {progressColor(resourceUsage.cpu_usage)}"></div>
          </div>
        {:else if stat.id === "memory" && resourceUsage}
          <div class="nx-progress mt-3">
            <div class="nx-progress-bar" style="width: {resourceUsage.memory_percent}%; background: {progressColor(resourceUsage.memory_percent)}"></div>
          </div>
        {:else if stat.id === "disk" && resourceUsage}
          <div class="nx-progress mt-3">
            <div class="nx-progress-bar" style="width: {resourceUsage.disk_percent}%; background: {progressColor(resourceUsage.disk_percent)}"></div>
          </div>
        {/if}
      </div>
    {/each}
  </div>

  <!-- Bottom Section -->
  <div class="grid grid-cols-3 gap-4">
    <!-- Recently Used -->
    <div class="col-span-2 nx-section">
      <div class="nx-section-header">
        <h3 class="text-sm font-medium text-nx-text">{t("dashboard.recently_used")}</h3>
        <span class="nx-badge">{recentEnvs.length}</span>
      </div>
      {#if recentEnvs.length > 0}
        <div class="overflow-x-auto">
          <table class="nx-table w-full">
            <thead>
              <tr>
                <th class="px-4 py-2.5">{t("environments.name")}</th>
                <th class="px-4 py-2.5">Version</th>
                <th class="px-4 py-2.5">{t("software.status")}</th>
              </tr>
            </thead>
            <tbody>
              {#each recentEnvs as env}
                <tr>
                  <td class="px-4 py-3 text-sm text-nx-text font-medium">{env.name}</td>
                  <td class="px-4 py-3">
                    <code class="nx-code">{env.version}</code>
                  </td>
                  <td class="px-4 py-3">
                    <span class="inline-flex items-center gap-1.5 text-xs text-nx-text-secondary">
                      <span class="nx-status-dot {env.statusColor}"></span>
                      {env.status}
                    </span>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {:else}
        <div class="nx-empty">
          <span class="material-symbols-outlined text-2xl text-nx-text-muted mb-2">code</span>
          <p class="text-xs text-nx-text-muted">No environments configured</p>
        </div>
      {/if}
    </div>

    <!-- System Health -->
    <div class="nx-section">
      <div class="nx-section-header">
        <h3 class="text-sm font-medium text-nx-text">{t("dashboard.system_health")}</h3>
      </div>
      <div class="p-4 space-y-4">
        {#if loading}
          <div class="flex items-center justify-center py-8">
            <span class="material-symbols-outlined nx-animate-spin text-nx-text-muted">progress_activity</span>
          </div>
        {:else if error}
          <div class="text-xs text-nx-text-muted">{error}</div>
        {:else if systemInfo && resourceUsage}
          <div>
            <div class="mb-0.5 text-[10px] font-medium text-nx-text-muted uppercase tracking-wider">{t("dashboard.operating_system")}</div>
            <div class="text-sm text-nx-text">{systemInfo.os_name} {systemInfo.os_version}</div>
            <div class="mt-0.5 text-xs text-nx-text-muted font-mono">{systemInfo.kernel_version}</div>
          </div>
          <div class="nx-divider"></div>
          <div>
            <div class="mb-0.5 text-[10px] font-medium text-nx-text-muted uppercase tracking-wider">{t("dashboard.cpu_usage")}</div>
            <div class="text-sm text-nx-text tabular-nums">{resourceUsage.cpu_usage.toFixed(1)}%</div>
            <div class="nx-progress mt-2">
              <div class="nx-progress-bar" style="width: {resourceUsage.cpu_usage}%; background: {progressColor(resourceUsage.cpu_usage)}"></div>
            </div>
          </div>
          <div class="nx-divider"></div>
          <div>
            <div class="mb-0.5 text-[10px] font-medium text-nx-text-muted uppercase tracking-wider">{t("dashboard.system_uptime")}</div>
            <div class="text-sm text-nx-text tabular-nums">{formatUptime(resourceUsage.uptime_secs)}</div>
          </div>
        {/if}
      </div>
    </div>
  </div>
</div>

// src/views/Dashboard.vue
<script setup>
import { ref, computed, onMounted, onBeforeUnmount } from "vue";
import { useRouter } from "vue-router";
import { invoke } from "@tauri-apps/api/core";
import { t } from "../lib/i18n.js";
import { friendlyError } from "../lib/errors.js";

const router = useRouter();

const systemInfo = ref(null);
const resourceUsage = ref(null);
const loading = ref(true);
const error = ref(null);
const environments = ref([]);

let timer = null;

function formatUptime(seconds) {
  const days = Math.floor(seconds / 86400);
  const hours = Math.floor((seconds % 86400) / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  return `${days}d ${hours}h ${minutes}m`;
}

async function loadSystemInfo() {
  try {
    loading.value = true;
    error.value = null;
    systemInfo.value = await invoke("get_system_info");
    resourceUsage.value = await invoke("get_resource_usage");
  } catch (err) {
    error.value = friendlyError(err);
  } finally {
    loading.value = false;
  }
}

async function refreshResourceUsage() {
  try {
    resourceUsage.value = await invoke("get_resource_usage");
  } catch (_) {}
}

async function loadEnvironments() {
  try {
    environments.value = await invoke("list_environments");
  } catch (_) {}
}

function progressColor(val) {
  if (val > 80) return "rgb(var(--red-6))";
  if (val > 60) return "rgb(var(--orange-6))";
  return "rgb(var(--green-6))";
}

const stats = computed(() => [
  {
    id: "cpu",
    tkey: "dashboard.cpu_cores",
    value: systemInfo.value ? String(systemInfo.value.cpu_cores) : "--",
    sub: systemInfo.value?.cpu_model
      ? systemInfo.value.cpu_model.split(" ").slice(0, 2).join(" ")
      : "",
    percent: resourceUsage.value ? resourceUsage.value.cpu_usage : null,
  },
  {
    id: "memory",
    tkey: "dashboard.memory",
    value: resourceUsage.value
      ? `${resourceUsage.value.memory_percent.toFixed(0)}%`
      : "--",
    sub: resourceUsage.value
      ? `${resourceUsage.value.memory_used_gb}GB / ${resourceUsage.value.memory_total_gb}GB`
      : "",
    percent: resourceUsage.value ? resourceUsage.value.memory_percent : null,
  },
  {
    id: "disk",
    tkey: "dashboard.disk",
    value: resourceUsage.value
      ? `${resourceUsage.value.disk_percent.toFixed(0)}%`
      : "--",
    sub: resourceUsage.value
      ? `${resourceUsage.value.disk_used_gb}GB / ${resourceUsage.value.disk_total_gb}GB`
      : "",
    percent: resourceUsage.value ? resourceUsage.value.disk_percent : null,
  },
]);

const recentEnvs = computed(() =>
  environments.value.slice(0, 5).map((env) => ({
    name: env.name,
    version: env.version,
    status: env.status === "Active" ? t("dashboard.running") : t("dashboard.stopped"),
    statusColor: env.status === "Active" ? "running" : "stopped",
  }))
);

onMounted(() => {
  loadSystemInfo();
  loadEnvironments();
  timer = setInterval(refreshResourceUsage, 5000);
});

onBeforeUnmount(() => {
  if (timer) clearInterval(timer);
});
</script>

<template>
  <div class="page">
    <!-- Header -->
    <div class="page-header">
      <div>
        <h1 class="page-title">{{ t("dashboard.overview") }}</h1>
        <p class="page-desc">{{ t("dashboard.status_at_a_glance") }}</p>
      </div>
      <a-button type="primary" @click="router.push('/environments')">
        <template #icon><icon-plus /></template>
        {{ t("dashboard.new_environment") }}
      </a-button>
    </div>

    <!-- Stats Cards -->
    <a-row :gutter="16" class="mb-5">
      <a-col v-for="stat in stats" :key="stat.id" :span="8">
        <a-card :bordered="true" class="stat-card">
          <div class="stat-head">
            <span class="stat-label">{{ t(stat.tkey) }}</span>
          </div>
          <div class="stat-value">{{ stat.value }}</div>
          <div class="stat-sub">{{ stat.sub }}</div>
          <a-progress
            v-if="stat.percent !== null"
            :percent="Math.min(stat.percent, 100)"
            :color="progressColor(stat.percent)"
            :show-text="false"
            class="stat-progress"
          />
        </a-card>
      </a-col>
    </a-row>

    <!-- Bottom Section -->
    <a-row :gutter="16">
      <!-- Recently Used -->
      <a-col :span="16">
        <a-card class="section-card" :bordered="true" title=" ">
          <template #title>
            <div class="card-title-row">
              <span>{{ t("dashboard.recently_used") }}</span>
              <a-tag size="small">{{ recentEnvs.length }}</a-tag>
            </div>
          </template>

          <a-empty v-if="recentEnvs.length === 0" :description="t('environments.no_data')">
            <template #image>
              <icon-code />
            </template>
          </a-empty>

          <a-table
            v-else
            :data="recentEnvs"
            :pagination="false"
            :bordered="{ wrapper: false, cell: false }"
            size="small"
          >
            <template #columns>
              <a-table-column title=" " data-index="name">
                <template #cell="{ record }">
                  <span class="env-name">{{ record.name }}</span>
                </template>
              </a-table-column>
              <a-table-column :title="t('version')" data-index="version">
                <template #cell="{ record }">
                  <a-typography-text code>{{ record.version }}</a-typography-text>
                </template>
              </a-table-column>
              <a-table-column :title="t('software.status')" data-index="status">
                <template #cell="{ record }">
                  <span class="env-status">
                    <span class="status-dot" :class="record.statusColor"></span>
                    {{ record.status }}
                  </span>
                </template>
              </a-table-column>
            </template>
          </a-table>
        </a-card>
      </a-col>

      <!-- System Health -->
      <a-col :span="8">
        <a-card class="section-card" :bordered="true">
          <template #title>{{ t("dashboard.system_health") }}</template>

          <a-spin v-if="loading" :loading="true" class="health-spin">
            <div style="height: 120px"></div>
          </a-spin>

          <div v-else-if="error" class="text-muted">{{ error }}</div>

          <template v-else-if="systemInfo && resourceUsage">
            <div class="health-block">
              <div class="health-label">{{ t("dashboard.operating_system") }}</div>
              <div class="health-value">
                {{ systemInfo.os_name }} {{ systemInfo.os_version }}
              </div>
              <div class="health-mono">{{ systemInfo.kernel_version }}</div>
            </div>
            <a-divider class="health-divider" />
            <div class="health-block">
              <div class="health-label">{{ t("dashboard.cpu_usage") }}</div>
              <div class="health-value">{{ resourceUsage.cpu_usage.toFixed(1) }}%</div>
              <a-progress
                :percent="Math.min(resourceUsage.cpu_usage, 100)"
                :color="progressColor(resourceUsage.cpu_usage)"
                :show-text="false"
                class="health-progress"
              />
            </div>
            <a-divider class="health-divider" />
            <div class="health-block">
              <div class="health-label">{{ t("dashboard.system_uptime") }}</div>
              <div class="health-value">{{ formatUptime(resourceUsage.uptime_secs) }}</div>
            </div>
          </template>
        </a-card>
      </a-col>
    </a-row>
  </div>
</template>

<style scoped>
.stat-card {
  border-radius: 10px;
}
.stat-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 6px;
}
.stat-label {
  font-size: 12px;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--color-text-2);
}
.stat-value {
  font-size: 26px;
  font-weight: 600;
  color: var(--color-text-1);
  letter-spacing: -0.02em;
}
.stat-sub {
  margin-top: 2px;
  font-size: 12px;
  color: var(--color-text-3);
}
.stat-progress {
  margin-top: 12px;
}

.card-title-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
.env-name {
  font-weight: 500;
  color: var(--color-text-1);
}
.env-status {
  display: inline-flex;
  align-items: center;
  font-size: 12px;
  color: var(--color-text-2);
}

.health-spin {
  display: block;
}
.health-block {
  margin-bottom: 2px;
}
.health-label {
  font-size: 10px;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--color-text-3);
  margin-bottom: 2px;
}
.health-value {
  font-size: 14px;
  color: var(--color-text-1);
}
.health-mono {
  margin-top: 2px;
  font-size: 12px;
  font-family: "JetBrains Mono", monospace;
  color: var(--color-text-3);
}
.health-divider {
  margin: 14px 0;
}
.health-progress {
  margin-top: 8px;
}
</style>
