// src/routes/Settings.svelte
<script>
  import { onMount } from "svelte";
  import { t, initI18n, getLang } from "../lib/i18n.svelte.js";
  import { invoke } from "@tauri-apps/api/core";
  import { navigate } from "../lib/stores.svelte.js";
  import { friendlyError } from "../lib/errors.svelte.js";

  let theme = $state("dark");
  let lang = $state(getLang());
  let compactMode = $state(false);
  let buildAlerts = $state(true);
  let securityNotices = $state(true);
  let proxyEnabled = $state(false);
  let proxyAddress = $state("");
  let proxyPort = $state("");
  let appVersion = $state("");

  let updateState = $state("idle");
  function isState(v) { return updateState === v; }
  let updateInfo = $state(null);
  let updateError = $state("");
  let changelogEn = $state("");
  let changelogZh = $state("");
  let downloadProgress = $state(0);

  function applyTheme(t) {
    document.documentElement.setAttribute("data-theme", t);
    localStorage.setItem("devnexus-theme", t);
  }

  function setTheme(t) {
    theme = t;
    if (t === "system") {
      const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
      applyTheme(prefersDark ? "dark" : "light");
    } else {
      applyTheme(t);
    }
  }

  async function setLang(l) {
    lang = l;
    await initI18n(l);
  }

  async function checkForUpdates() {
    updateState = "checking";
    updateError = "";
    updateInfo = null;
    changelogEn = "";
    changelogZh = "";
    try {
      const result = await invoke("check_for_updates_github");
      if (result.has_update) {
        updateInfo = result;
        const cl = await invoke("get_changelog", { version: null });
        if (cl) {
          changelogEn = cl.en;
          changelogZh = cl.zh;
        }
        updateState = "available";
      } else {
        updateState = "up_to_date";
      }
    } catch (err) {
      updateError = friendlyError(err);
      updateState = "error";
    }
  }

  async function downloadAndInstall() {
    updateState = "downloading";
    downloadProgress = 0;
    updateError = "";
    try {
      const { check } = await import("@tauri-apps/plugin-updater");
      const update = await check();
      if (update) {
        let totalBytes = 0;
        let downloadedBytes = 0;
        await update.downloadAndInstall((event) => {
          if (event.event === "Started" && event.data.contentLength) totalBytes = event.data.contentLength;
          else if (event.event === "Progress") { downloadedBytes += event.data.chunkLength; downloadProgress = totalBytes > 0 ? Math.round((downloadedBytes / totalBytes) * 100) : 0; }
          else if (event.event === "Finished") downloadProgress = 100;
        });
        updateState = "installed";
        return;
      }
    } catch (_) {}

    try {
      const url = await invoke("get_download_url", { version: updateInfo?.latest_version || "" });
      const { open } = await import("@tauri-apps/plugin-shell");
      await open(url);
      updateState = "opened";
    } catch (fallbackErr) {
      try {
        const { open } = await import("@tauri-apps/plugin-shell");
        await open(updateInfo?.html_url || `https://github.com/linanwanttodo/DevNexus/releases/latest`);
        updateState = "opened";
      } catch (e) {
        updateError = friendlyError(e);
        updateState = "error";
      }
    }
  }

  async function restartApp() {
    try {
      const { relaunch } = await import("@tauri-apps/plugin-process");
      await relaunch();
    } catch (e) { updateError = friendlyError(e); }
  }

  onMount(() => {
    const saved = localStorage.getItem("devnexus-theme") || "dark";
    theme = saved === "light" || saved === "dark" ? saved : "system";
    setTheme(theme);
    invoke("get_app_version").then(v => appVersion = v).catch(() => appVersion = "1.1.1");
  });
</script>

<div class="nx-page flex h-full flex-col">
  <!-- Header with back button -->
  <div class="flex items-center gap-2 border-b border-nx-border px-5 py-2.5">
    <button class="nx-back-btn" onclick={() => navigate("/dashboard")}>
      <span class="material-symbols-outlined text-lg">arrow_back</span>
      {t("nav.dashboard")}
    </button>
    <span class="text-xs text-nx-text-muted">/</span>
    <h1 class="text-sm font-medium text-nx-text">{t("settings.title")}</h1>
  </div>

  <!-- Content -->
  <div class="flex-1 overflow-y-auto">
    <div class="mx-auto max-w-2xl px-5 py-6 space-y-4">
      <!-- Appearance -->
      <div class="nx-section">
        <div class="nx-section-header">
          <h3 class="text-sm font-medium text-nx-text">{t("settings.appearance")}</h3>
        </div>
        <div class="nx-section-body space-y-4">
          <!-- Theme -->
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-nx-text">{t("settings.theme")}</div>
              <div class="text-xs text-nx-text-muted">{t("settings.theme_desc")}</div>
            </div>
            <div class="flex rounded-md border border-nx-border overflow-hidden bg-nx-raised">
              <button
                class="px-3 py-1.5 text-xs font-medium transition-colors {theme === 'light' ? 'bg-nx-overlay text-nx-text shadow-sm' : 'text-nx-text-secondary hover:text-nx-text'}"
                onclick={() => setTheme("light")}>{t("settings.light")}</button>
              <button
                class="border-x border-nx-border px-3 py-1.5 text-xs font-medium transition-colors {theme === 'dark' ? 'bg-nx-overlay text-nx-text shadow-sm' : 'text-nx-text-secondary hover:text-nx-text'}"
                onclick={() => setTheme("dark")}>{t("settings.dark")}</button>
              <button
                class="px-3 py-1.5 text-xs font-medium transition-colors {theme === 'system' ? 'bg-nx-overlay text-nx-text shadow-sm' : 'text-nx-text-secondary hover:text-nx-text'}"
                onclick={() => setTheme("system")}>{t("settings.system")}</button>
            </div>
          </div>

          <div class="nx-divider"></div>

          <!-- Compact Mode -->
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-nx-text">{t("settings.compact_mode")}</div>
              <div class="text-xs text-nx-text-muted">{t("settings.compact_mode_desc")}</div>
            </div>
            <button
              class="nx-toggle"
              role="switch"
              aria-label={t("settings.compact_mode")}
              aria-checked={compactMode}
              onclick={() => compactMode = !compactMode}>
            </button>
          </div>
        </div>
      </div>

      <!-- Language -->
      <div class="nx-section">
        <div class="nx-section-header">
          <h3 class="text-sm font-medium text-nx-text">{t("settings.language")}</h3>
        </div>
        <div class="nx-section-body">
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-nx-text">{t("settings.language_desc")}</div>
            </div>
            <select
              value={lang}
              onchange={(e) => setLang(e.currentTarget.value)}
              class="nx-input h-9 text-sm min-w-[130px]"
            >
              <option value="en">English</option>
              <option value="zh">中文</option>
              <option value="ru">Русский</option>
            </select>
          </div>
        </div>
      </div>

      <!-- Notifications -->
      <div class="nx-section">
        <div class="nx-section-header">
          <h3 class="text-sm font-medium text-nx-text">{t("settings.notifications")}</h3>
        </div>
        <div class="nx-section-body space-y-4">
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-nx-text">{t("settings.build_alerts")}</div>
              <div class="text-xs text-nx-text-muted">{t("settings.build_alerts_desc")}</div>
            </div>
            <button class="nx-toggle" role="switch" aria-label={t("settings.build_alerts")} aria-checked={buildAlerts} onclick={() => buildAlerts = !buildAlerts}></button>
          </div>
          <div class="nx-divider"></div>
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-nx-text">{t("settings.security_notices")}</div>
              <div class="text-xs text-nx-text-muted">{t("settings.security_notices_desc")}</div>
            </div>
            <button class="nx-toggle" role="switch" aria-label={t("settings.security_notices")} aria-checked={securityNotices} onclick={() => securityNotices = !securityNotices}></button>
          </div>
        </div>
      </div>

      <!-- Network Proxy -->
      <div class="nx-section">
        <div class="nx-section-header">
          <h3 class="text-sm font-medium text-nx-text">{t("settings.network_proxy")}</h3>
        </div>
        <div class="nx-section-body space-y-4">
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-nx-text">{t("settings.enable_proxy")}</div>
              <div class="text-xs text-nx-text-muted">{t("settings.enable_proxy_desc")}</div>
            </div>
            <button class="nx-toggle" role="switch" aria-label={t("settings.enable_proxy")} aria-checked={proxyEnabled} onclick={() => proxyEnabled = !proxyEnabled}></button>
          </div>

          {#if proxyEnabled}
            <div class="grid grid-cols-3 gap-3">
              <div class="col-span-2">
                <label class="mb-1.5 block text-xs text-nx-text-muted" for="proxy-address">{t("settings.proxy_address")}</label>
                <input id="proxy-address" type="text" bind:value={proxyAddress} placeholder="127.0.0.1"
                  class="nx-input w-full h-9 text-sm" />
              </div>
              <div>
                <label class="mb-1.5 block text-xs text-nx-text-muted" for="proxy-port">{t("settings.port")}</label>
                <input id="proxy-port" type="text" bind:value={proxyPort} placeholder="7890"
                  class="nx-input w-full h-9 text-sm" />
              </div>
            </div>
          {/if}
        </div>
      </div>

      <!-- Updates -->
      <div class="nx-section">
        <div class="nx-section-header">
          <h3 class="text-sm font-medium text-nx-text">{t("settings.updates")}</h3>
        </div>
        <div class="nx-section-body">
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-nx-text">{t("settings.current_version")}</div>
              <div class="font-mono text-xs text-nx-text-secondary">v{appVersion || "—"}</div>
            </div>
            <button class="nx-btn nx-btn-ghost h-8 text-xs"
              onclick={checkForUpdates}
              disabled={isState('checking') || isState('downloading')}>
              {#if isState('checking')}
                <span class="material-symbols-outlined text-sm nx-animate-spin">refresh</span>
                {t("settings.checking")}
              {:else}
                {t("settings.check_updates")}
              {/if}
            </button>
          </div>

          <div class="mt-3">
            {#if isState('checking')}
              <div class="flex items-center gap-2"><span class="material-symbols-outlined text-nx-text-secondary text-sm nx-animate-spin">refresh</span><span class="text-xs text-nx-text-secondary">{t("settings.checking")}...</span></div>
            {:else if isState('up_to_date')}
              <div class="flex items-center gap-2"><span class="material-symbols-outlined text-nx-success text-sm">check_circle</span><span class="text-xs text-nx-text-secondary">{t("settings.up_to_date")}</span></div>
            {:else if isState('available')}
              <div class="mt-2 rounded-lg border border-nx-border bg-nx-bg p-3">
                <div class="flex items-start gap-2">
                  <span class="material-symbols-outlined text-nx-accent text-sm mt-0.5">system_update</span>
                  <div class="flex-1 min-w-0">
                    <div class="text-sm font-medium text-nx-text">{t("settings.update_available")} {updateInfo?.latest_version}</div>
                    {#if changelogEn || changelogZh}
                      <div class="mt-1 space-y-1">
                        {#if changelogEn}
                          <div class="text-xs font-medium text-nx-text mt-1">English</div>
                          <div class="max-h-24 overflow-y-auto text-xs text-nx-text-secondary whitespace-pre-wrap leading-relaxed">{changelogEn}</div>
                        {/if}
                        {#if changelogZh}
                          <div class="text-xs font-medium text-nx-text mt-2">中文</div>
                          <div class="max-h-24 overflow-y-auto text-xs text-nx-text-secondary whitespace-pre-wrap leading-relaxed">{changelogZh}</div>
                        {/if}
                      </div>
                    {:else if updateInfo?.release_notes}
                      <div class="mt-1 max-h-20 overflow-y-auto text-xs text-nx-text-secondary whitespace-pre-wrap">{updateInfo.release_notes}</div>
                    {/if}
                    {#if updateInfo?.published_at}<div class="mt-1 text-xs text-nx-text-muted">{t("settings.released")}: {new Date(updateInfo.published_at).toLocaleDateString()}</div>{/if}
                  </div>
                </div>
                <button class="nx-btn nx-btn-primary w-full mt-3 h-8 text-xs" onclick={downloadAndInstall}>
                  <span class="material-symbols-outlined text-sm">download</span>{t("settings.download_update")}
                </button>
              </div>
            {:else if isState('downloading')}
              <div class="flex flex-col gap-2">
                <div class="flex items-center gap-2">
                  <span class="material-symbols-outlined text-nx-accent text-sm nx-animate-spin">progress_activity</span>
                  <span class="text-xs text-nx-text-secondary">{t("settings.downloading")}...</span>
                  {#if downloadProgress > 0}<span class="text-[10px] text-nx-text-muted tabular-nums">{downloadProgress}%</span>{/if}
                </div>
                <div class="nx-progress">
                  <div class="nx-progress-bar accent transition-all" style="width: {downloadProgress}%"></div>
                </div>
              </div>
            {:else if isState('installed')}
              <div class="flex items-center gap-2">
                <span class="material-symbols-outlined text-nx-success text-sm">check_circle</span>
                <span class="text-xs text-nx-text-secondary">{t("settings.update_installed")}</span>
                <button class="nx-btn text-xs h-6 px-2 text-nx-success" onclick={restartApp}>{t("settings.restart_now")}</button>
              </div>
            {:else if isState('error')}
              <div class="flex items-center gap-2"><span class="material-symbols-outlined text-nx-danger text-sm">error</span><span class="text-xs text-nx-danger">{t("settings.update_error")}: {updateError}</span></div>
            {:else if isState('opened')}
              <div class="flex items-center gap-2"><span class="material-symbols-outlined text-nx-success text-sm">check_circle</span><span class="text-xs text-nx-text-secondary">{t("settings.download_opened")}</span></div>
            {:else}
              <div class="flex items-center gap-2"><span class="material-symbols-outlined text-nx-text-muted text-sm">info</span><span class="text-xs text-nx-text-muted">{t("settings.click_to_check")}</span></div>
            {/if}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// src/views/Settings.vue
<script setup>
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import { invoke } from "@tauri-apps/api/core";
import { t, initI18n, getLang } from "../lib/i18n.js";
import { setTheme } from "../lib/stores.js";
import { friendlyError } from "../lib/errors.js";

const router = useRouter();

const themePref = ref("dark");
const lang = ref(getLang().value);
const compactMode = ref(false);
const buildAlerts = ref(true);
const securityNotices = ref(true);
const proxyEnabled = ref(false);
const proxyAddress = ref("");
const proxyPort = ref("");
const appVersion = ref("");

const updateState = ref("idle");
const updateInfo = ref(null);
const updateError = ref("");
const changelogEn = ref("");
const changelogZh = ref("");
const downloadProgress = ref(0);

function isState(v) {
  return updateState.value === v;
}

function setThemePref(t) {
  themePref.value = t;
  setTheme(t);
}

async function setLang(l) {
  lang.value = l;
  await initI18n(l);
}

async function checkForUpdates() {
  updateState.value = "checking";
  updateError.value = "";
  updateInfo.value = null;
  changelogEn.value = "";
  changelogZh.value = "";
  try {
    const result = await invoke("check_for_updates_github");
    if (result.has_update) {
      updateInfo.value = result;
      try {
        const cl = await invoke("get_changelog", { version: null });
        if (cl) {
          changelogEn.value = cl.en;
          changelogZh.value = cl.zh;
        }
      } catch (_) {}
      updateState.value = "available";
    } else {
      updateState.value = "up_to_date";
    }
  } catch (err) {
    updateError.value = friendlyError(err);
    updateState.value = "error";
  }
}

async function downloadAndInstall() {
  updateState.value = "downloading";
  downloadProgress.value = 0;
  updateError.value = "";
  try {
    const { check } = await import("@tauri-apps/plugin-updater");
    const update = await check();
    if (update) {
      let totalBytes = 0;
      let downloadedBytes = 0;
      await update.downloadAndInstall((event) => {
        if (event.event === "Started" && event.data.contentLength)
          totalBytes = event.data.contentLength;
        else if (event.event === "Progress") {
          downloadedBytes += event.data.chunkLength;
          downloadProgress.value =
            totalBytes > 0 ? Math.round((downloadedBytes / totalBytes) * 100) : 0;
        } else if (event.event === "Finished") downloadProgress.value = 100;
      });
      updateState.value = "installed";
      return;
    }
  } catch (_) {}

  try {
    const url = await invoke("get_download_url", {
      version: updateInfo.value?.latest_version || "",
    });
    const { open } = await import("@tauri-apps/plugin-shell");
    await open(url);
    updateState.value = "opened";
  } catch (fallbackErr) {
    try {
      const { open } = await import("@tauri-apps/plugin-shell");
      await open(
        updateInfo.value?.html_url ||
          "https://github.com/linanwanttodo/DevNexus/releases/latest"
      );
      updateState.value = "opened";
    } catch (e) {
      updateError.value = friendlyError(e);
      updateState.value = "error";
    }
  }
}

async function restartApp() {
  try {
    const { relaunch } = await import("@tauri-apps/plugin-process");
    await relaunch();
  } catch (e) {
    updateError.value = friendlyError(e);
  }
}

onMounted(() => {
  const saved = localStorage.getItem("devnexus-theme") || "dark";
  themePref.value =
    saved === "light" || saved === "dark" ? saved : "system";
  setTheme(themePref.value);
  invoke("get_app_version")
    .then((v) => (appVersion.value = v))
    .catch(() => (appVersion.value = "1.1.1"));
});
</script>

<template>
  <div class="page settings-page">
    <!-- Header with back button -->
    <div class="breadcrumb">
      <a-button type="text" size="small" class="back-btn" @click="router.push('/dashboard')">
        <template #icon><icon-left /></template>
        {{ t("nav.dashboard") }}
      </a-button>
      <span class="crumb-sep">/</span>
      <span class="crumb-title">{{ t("settings.title") }}</span>
    </div>

    <!-- Content -->
    <div class="settings-content">
      <!-- Appearance -->
      <a-card :bordered="true" class="section-card" :title="t('settings.appearance')">
        <a-space direction="vertical" :size="16" fill>
          <div class="setting-row">
            <div>
              <div class="setting-label">{{ t("settings.theme") }}</div>
              <div class="setting-desc">{{ t("settings.theme_desc") }}</div>
            </div>
            <a-radio-group v-model="themePref" type="button" @change="(v) => setThemePref(v)">
              <a-radio value="light">{{ t("settings.light") }}</a-radio>
              <a-radio value="dark">{{ t("settings.dark") }}</a-radio>
              <a-radio value="system">{{ t("settings.system") }}</a-radio>
            </a-radio-group>
          </div>

          <a-divider class="setting-divider" />

          <div class="setting-row">
            <div>
              <div class="setting-label">{{ t("settings.compact_mode") }}</div>
              <div class="setting-desc">{{ t("settings.compact_mode_desc") }}</div>
            </div>
            <a-switch v-model="compactMode" />
          </div>
        </a-space>
      </a-card>

      <!-- Language -->
      <a-card :bordered="true" class="section-card" :title="t('settings.language')">
        <div class="setting-row">
          <div>
            <div class="setting-label">{{ t("settings.language_desc") }}</div>
          </div>
          <a-select v-model="lang" style="width: 160px" @change="setLang">
            <a-option value="en">English</a-option>
            <a-option value="zh">中文</a-option>
            <a-option value="ru">Русский</a-option>
          </a-select>
        </div>
      </a-card>

      <!-- Notifications -->
      <a-card :bordered="true" class="section-card" :title="t('settings.notifications')">
        <a-space direction="vertical" :size="16" fill>
          <div class="setting-row">
            <div>
              <div class="setting-label">{{ t("settings.build_alerts") }}</div>
              <div class="setting-desc">{{ t("settings.build_alerts_desc") }}</div>
            </div>
            <a-switch v-model="buildAlerts" />
          </div>
          <a-divider class="setting-divider" />
          <div class="setting-row">
            <div>
              <div class="setting-label">{{ t("settings.security_notices") }}</div>
              <div class="setting-desc">{{ t("settings.security_notices_desc") }}</div>
            </div>
            <a-switch v-model="securityNotices" />
          </div>
        </a-space>
      </a-card>

      <!-- Network Proxy -->
      <a-card :bordered="true" class="section-card" :title="t('settings.network_proxy')">
        <a-space direction="vertical" :size="16" fill>
          <div class="setting-row">
            <div>
              <div class="setting-label">{{ t("settings.enable_proxy") }}</div>
              <div class="setting-desc">{{ t("settings.enable_proxy_desc") }}</div>
            </div>
            <a-switch v-model="proxyEnabled" />
          </div>

          <a-row v-if="proxyEnabled" :gutter="12">
            <a-col :span="16">
              <label class="input-label" for="proxy-address">{{ t("settings.proxy_address") }}</label>
              <a-input id="proxy-address" v-model="proxyAddress" placeholder="127.0.0.1" />
            </a-col>
            <a-col :span="8">
              <label class="input-label" for="proxy-port">{{ t("settings.port") }}</label>
              <a-input id="proxy-port" v-model="proxyPort" placeholder="7890" />
            </a-col>
          </a-row>
        </a-space>
      </a-card>

      <!-- Updates -->
      <a-card :bordered="true" class="section-card" :title="t('settings.updates')">
        <div class="setting-row">
          <div>
            <div class="setting-label">{{ t("settings.current_version") }}</div>
            <div class="version-mono">v{{ appVersion || "—" }}</div>
          </div>
          <a-button
            size="small"
            @click="checkForUpdates"
            :loading="isState('checking')"
            :disabled="isState('downloading')"
          >
            {{ t("settings.check_updates") }}
          </a-button>
        </div>

        <div class="update-status">
          <a-spin v-if="isState('checking')" :size="14" style="margin-right: 8px" />
          <a-result v-if="isState('up_to_date')" :status="'success'" class="inline-result">
            <template #title>{{ t("settings.up_to_date") }}</template>
          </a-result>

          <div v-else-if="isState('available')" class="update-card">
            <div class="update-head">
              <icon-sync class="update-icon" />
              <div class="update-info">
                <div class="update-title">
                  {{ t("settings.update_available") }} {{ updateInfo?.latest_version }}
                </div>
                <div v-if="changelogEn || changelogZh" class="changelog">
                  <template v-if="changelogEn">
                    <div class="changelog-lang">English</div>
                    <pre class="changelog-body">{{ changelogEn }}</pre>
                  </template>
                  <template v-if="changelogZh">
                    <div class="changelog-lang">中文</div>
                    <pre class="changelog-body">{{ changelogZh }}</pre>
                  </template>
                </div>
                <div v-else-if="updateInfo?.release_notes" class="changelog">
                  <pre class="changelog-body">{{ updateInfo.release_notes }}</pre>
                </div>
                <div v-if="updateInfo?.published_at" class="update-date">
                  {{ t("settings.released") }}: {{ new Date(updateInfo.published_at).toLocaleDateString() }}
                </div>
              </div>
            </div>
            <a-button type="primary" long @click="downloadAndInstall">
              <template #icon><icon-download /></template>
              {{ t("settings.download_update") }}
            </a-button>
          </div>

          <div v-else-if="isState('downloading')" class="download-block">
            <div class="download-row">
              <a-spin :size="14" />
              <span>{{ t("settings.downloading") }}...</span>
              <span v-if="downloadProgress > 0" class="download-pct">{{ downloadProgress }}%</span>
            </div>
            <a-progress :percent="downloadProgress" :show-text="false" />
          </div>

          <div v-else-if="isState('installed')" class="inline-success">
            <icon-check-circle-fill class="success-icon" />
            <span>{{ t("settings.update_installed") }}</span>
            <a-button type="text" size="small" @click="restartApp">
              {{ t("settings.restart_now") }}
            </a-button>
          </div>

          <div v-else-if="isState('error')" class="inline-error">
            <icon-close-circle-fill class="error-icon" />
            <span>{{ t("settings.update_error") }}: {{ updateError }}</span>
          </div>

          <div v-else-if="isState('opened')" class="inline-success">
            <icon-check-circle-fill class="success-icon" />
            <span>{{ t("settings.download_opened") }}</span>
          </div>

          <div v-else class="inline-idle">
            <icon-info-circle class="idle-icon" />
            <span>{{ t("settings.click_to_check") }}</span>
          </div>
        </div>
      </a-card>
    </div>
  </div>
</template>

<style scoped>
.settings-page {
  padding: 20px 24px;
}
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 8px;
  padding-bottom: 14px;
  margin-bottom: 16px;
  border-bottom: 1px solid var(--color-border);
}
.crumb-sep {
  font-size: 12px;
  color: var(--color-text-3);
}
.crumb-title {
  font-size: 14px;
  font-weight: 500;
  color: var(--color-text-1);
}
.settings-content {
  max-width: 640px;
}
.setting-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}
.setting-label {
  font-size: 14px;
  color: var(--color-text-1);
}
.setting-desc {
  font-size: 12px;
  color: var(--color-text-3);
  margin-top: 2px;
}
.setting-divider {
  margin: 2px 0;
}
.input-label {
  display: block;
  font-size: 12px;
  color: var(--color-text-3);
  margin-bottom: 6px;
}
.version-mono {
  font-family: "JetBrains Mono", monospace;
  font-size: 12px;
  color: var(--color-text-2);
  margin-top: 2px;
}
.update-status {
  margin-top: 16px;
}
.update-card {
  border: 1px solid var(--color-border);
  border-radius: 8px;
  background-color: var(--color-fill-1);
  padding: 12px;
}
.update-head {
  display: flex;
  gap: 10px;
  margin-bottom: 12px;
}
.update-icon {
  font-size: 16px;
  color: var(--color-primary-6);
  margin-top: 2px;
}
.update-info {
  flex: 1;
  min-width: 0;
}
.update-title {
  font-size: 14px;
  font-weight: 500;
  color: var(--color-text-1);
}
.changelog {
  margin-top: 6px;
}
.changelog-lang {
  font-size: 12px;
  font-weight: 500;
  color: var(--color-text-1);
  margin-top: 6px;
}
.changelog-body {
  max-height: 100px;
  overflow-y: auto;
  margin: 4px 0 0;
  white-space: pre-wrap;
  font-family: inherit;
  font-size: 12px;
  color: var(--color-text-2);
}
.update-date {
  margin-top: 6px;
  font-size: 12px;
  color: var(--color-text-3);
}
.download-block {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.download-row {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: var(--color-text-2);
}
.download-pct {
  font-family: "JetBrains Mono", monospace;
  font-size: 11px;
  color: var(--color-text-3);
}
.inline-success,
.inline-error,
.inline-idle {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}
.success-icon {
  color: rgb(var(--green-6));
}
.error-icon {
  color: rgb(var(--red-6));
}
.idle-icon {
  color: var(--color-text-3);
}
</style>
